Part of aboutMe Section
SoftRyzen-internship/ambidexter pull request #10
Opened 2023-08-18 10:14 UTC by ginkosoul

2023-08-18 12:49 UTC, BogdanGlazkov requested changes

2023-08-18 12:49 UTC, BogdanGlazkov commented on src/components/AdvantageCard/AdvantageCard.jsx
> +export function AdvantageCard({ count, text, list }) {
В проєкті ми використовуємо export const arrow function

2023-08-18 12:49 UTC, BogdanGlazkov commented on src/components/AdvantageCard/AdvantageCard.jsx
> +      className={`py-4 xl:py-8 px-3 md:px-4 bg-accent rounded-[10px] ${
Верстка в пікселях: py-[16px]

2023-08-18 12:49 UTC, BogdanGlazkov commented on src/components/AdvantageCard/AdvantageCard.jsx
> +        className={`text-black text-xs xl:text-2xl font-medium flex items-center gap-2 ${
Для розміру тексту в файлі конфіг у fontSize є змінні. gap  також у пікселях

2023-08-18 12:49 UTC, BogdanGlazkov commented on src/components/AdvantageCard/AdvantageCard.jsx
> +        <span className="text-[64px]/[1] md:text-[70px] xl:text-[140px] font-medium">
Замість text-[64px]/[1] краще text-large64

2023-08-18 12:49 UTC, BogdanGlazkov commented on src/components/AdvantageCard/AdvantageCard.jsx
> +      {list && (
Використовуємо тернарник list ? ul : null

2023-08-18 12:49 UTC, BogdanGlazkov commented on src/components/AdvantageCard/AdvantageCard.jsx
> +          {list.map((e, i) => (
Треба змінні називати описово, щоб іншим розробникам було зрозуміло що це. Напр. goal, school, index

2023-08-18 12:49 UTC, BogdanGlazkov commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +      <SectionTitle text={title} />
Додати нижні відступи + велику літеру

2023-08-18 12:49 UTC, BogdanGlazkov commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +                className={`text-black text-xs xl:text-2xl font-medium flex gap-3 xl:gap-2 pl-6 md:pl-[34px] xl:pl-[30px] items-baseline relative ${
До тексту використати клас mainText з css

2023-08-18 12:49 UTC, BogdanGlazkov commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +            {subTitle}
Перевірити line-height

2023-08-18 13:16 UTC, nadiakhoptiuk commented on src/components/AdvantageCard/AdvantageCard.jsx
> +      className={`py-4 xl:py-8 px-3 md:px-4 bg-accent rounded-[10px] ${
тут вірно, це властивість з тейлвінда, це якщо кастомні, тоді додаються з дужками і пікселями

2023-08-18 13:17 UTC, nadiakhoptiuk commented on src/components/AdvantageCard/AdvantageCard.jsx
> +        className={`text-black text-xs xl:text-2xl font-medium flex items-center gap-2 ${
змінні +, gap -

2023-08-18 16:15 UTC, nadiakhoptiuk requested changes

2023-08-18 16:15 UTC, nadiakhoptiuk commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +      {
фігурні дужки зайві

2023-08-18 16:15 UTC, nadiakhoptiuk commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +        <div className="p-4 w-full md:w-[calc(50%-10px)]">
перевірити падінги (на таблеті інші по y, на моб їх нема)

2023-08-18 16:15 UTC, nadiakhoptiuk commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +      <div className="md:flex md:gap-5 md:items-center mb-3 md:mb-5">
перевірити щоб блоки по висоті співпадали (таблет, декстоп)

2023-08-18 16:15 UTC, nadiakhoptiuk commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +                className={`text-black text-xs xl:text-2xl font-medium flex gap-3 xl:gap-2 pl-6 md:pl-[34px] xl:pl-[30px] items-baseline relative ${
вже не актуально

2023-08-18 18:21 UTC, BogdanGlazkov commented
{goals.map((e, i, { length }) => назви описові: goal, index

2023-08-18 19:01 UTC, ginkosoul commented on src/components/AdvantageCard/AdvantageCard.jsx
> +export function AdvantageCard({ count, text, list }) {
done

2023-08-18 19:01 UTC, ginkosoul commented on src/components/AdvantageCard/AdvantageCard.jsx
> +      className={`py-4 xl:py-8 px-3 md:px-4 bg-accent rounded-[10px] ${
done... twice...

2023-08-18 19:02 UTC, ginkosoul commented on src/components/AdvantageCard/AdvantageCard.jsx
> +        className={`text-black text-xs xl:text-2xl font-medium flex items-center gap-2 ${
done

2023-08-18 19:02 UTC, ginkosoul commented on src/components/AdvantageCard/AdvantageCard.jsx
> +        <span className="text-[64px]/[1] md:text-[70px] xl:text-[140px] font-medium">
done

2023-08-18 19:02 UTC, ginkosoul commented on src/components/AdvantageCard/AdvantageCard.jsx
> +          {list.map((e, i) => (
done

2023-08-18 19:06 UTC, ginkosoul commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +                className={`text-black text-xs xl:text-2xl font-medium flex gap-3 xl:gap-2 pl-6 md:pl-[34px] xl:pl-[30px] items-baseline relative ${
accepted

2023-08-18 19:08 UTC, ginkosoul commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +      {
+

2023-08-18 19:08 UTC, ginkosoul commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +        <div className="p-4 w-full md:w-[calc(50%-10px)]">
+

2023-08-18 19:08 UTC, ginkosoul commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +      <div className="md:flex md:gap-5 md:items-center mb-3 md:mb-5">
+

2023-08-18 19:12 UTC, ginkosoul commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +      <SectionTitle text={title} />
done partially. Finished in another branch

2023-08-19 11:35 UTC, BogdanGlazkov requested changes
Зовсім дрібні зауваження, + виправ також назву гілки)

2023-08-19 11:35 UTC, BogdanGlazkov commented on src/components/AdvantageCard/AdvantageCard.jsx
> +      className={`py-4 xl:py-8 px-3 md:px-4 bg-accent rounded-[10px] ${
Для border-radius 10px у конфігу є кастомний клас rounded-10

2023-08-19 11:35 UTC, BogdanGlazkov commented on src/components/AdvantageCard/AdvantageCard.jsx
> +          {advantagesList.map((e, i) => (
Розшифрувати назви змінних

2023-08-19 11:35 UTC, BogdanGlazkov commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +    <section className="container">
Є компонент Контейнер, який ми імпортуємо у кожну секцію

2023-08-19 11:35 UTC, BogdanGlazkov commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +        <div className="border-accent border rounded-[10px] w-full md:w-[calc(50%-10px)] h-[calc(((min(100vw,480px)-40px)/280)*191)] md:h-[227px] xl:h-[428px] max-md:mb-3"></div>
rounded-10

2023-08-19 11:35 UTC, BogdanGlazkov commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +            {subTitle}
Не зроблено. На десктопі line-height має бути більше

2023-08-19 15:41 UTC, ginkosoul commented on src/components/AdvantageCard/AdvantageCard.jsx
> +          {advantagesList.map((e, i) => (
+

2023-08-19 15:41 UTC, ginkosoul commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +    <section className="container">
+

2023-08-19 15:41 UTC, ginkosoul commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +        <div className="border-accent border rounded-[10px] w-full md:w-[calc(50%-10px)] h-[calc(((min(100vw,480px)-40px)/280)*191)] md:h-[227px] xl:h-[428px] max-md:mb-3"></div>
+

2023-08-19 16:44 UTC, BogdanGlazkov approved these changes
Ок. Только подправь название ветки плиз

2023-08-20 09:07 UTC, nadiakhoptiuk requested changes

2023-08-20 09:07 UTC, nadiakhoptiuk commented on src/app/[locale]/page.jsx
> +import { AboutMeSection } from '@/sections';
тут обидві секції будуть у одному рядку імпортуватися

2023-08-20 09:07 UTC, nadiakhoptiuk commented on src/components/AdvantageCard/AdvantageCard.jsx
> +              {'▪ '}
булети додаються/змінюються через css

2023-08-20 09:07 UTC, nadiakhoptiuk commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +        <SectionTitle text={title} />
робіть більше відступів, читабельніше буде

2023-08-20 09:07 UTC, nadiakhoptiuk commented on src/components/AdvantageCard/AdvantageCard.jsx
> +        advantagesList && 'row-span-2'
переписати через тернарник і пустий рядок, бо на сторінці приміняє undefined

2023-08-20 09:07 UTC, nadiakhoptiuk commented on src/components/AdvantageCard/AdvantageCard.jsx
> +          advantagesList && 'mb-2'
переписати через тернарник і пустий рядок, бо на сторінці приміняє undefined

2023-08-20 11:31 UTC, ginkosoul commented on src/components/AdvantageCard/AdvantageCard.jsx
> +              {'▪ '}
на цьому компоненті макет не дуже... витратив, мабуть, хвилин 30 тільки на відступи між ліжками(через lineheight підбирав)... спробую... відступи та розміри на око підбиратиму

2023-08-21 09:43 UTC, ginkosoul commented on src/app/[locale]/page.jsx
> +import { AboutMeSection } from '@/sections';
+

2023-08-21 09:43 UTC, ginkosoul commented on src/components/AdvantageCard/AdvantageCard.jsx
> +              {'▪ '}
+

2023-08-21 09:43 UTC, ginkosoul commented on src/components/AdvantageCard/AdvantageCard.jsx
> +        advantagesList && 'row-span-2'
+

2023-08-21 09:43 UTC, ginkosoul commented on src/components/AdvantageCard/AdvantageCard.jsx
> +          advantagesList && 'mb-2'
+

2023-08-21 09:45 UTC, ginkosoul commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +        <SectionTitle text={title} />
Табуляція?.. то prettier, здається...

2023-08-21 09:49 UTC, nadiakhoptiuk approved these changes

2023-08-21 09:49 UTC, nadiakhoptiuk commented on src/sections/AboutMeSection/AboutMeSection.jsx
> +        <SectionTitle text={title} />
мала на увазі рядки, відступи вниз

2023-08-21 09:50 UTC, merged