added svg as :after in SectionTitle component
SoftRyzen-internship/ambidexter pull request #12
Opened 2023-08-18 19:30 UTC by ginkosoul

2023-08-19 11:01 UTC, BogdanGlazkov approved these changes
Good

2023-08-20 07:55 UTC, nadiakhoptiuk requested changes

2023-08-20 07:55 UTC, nadiakhoptiuk commented on src/app/[locale]/globals.css
> +  --arrow-image: url('../../../public/icons/arrow-down.svg');
краще винести у конфіг тейлвінда, у властивість content, щоб всі змінні знаходились там
[посилання](https://tailwindcss.com/docs/content#using-custom-values)

2023-08-20 07:55 UTC, nadiakhoptiuk commented on src/components/SectionTitle/SectionTitle.jsx
> +      className={`text-center mb-[16px] md:mb-[36px] ${className}
додавати змінну className потрібно в кінець рядка, це читабельніше, і потрібно для того, щоб стилі не перебивалися тими, які тут внизу.

2023-08-20 17:40 UTC, ginkosoul commented on src/app/[locale]/globals.css
> +  --arrow-image: url('../../../public/icons/arrow-down.svg');
Чомусь не працює цей спосіб... можливо через Next... поки Олексій допоміг зробити посилання, яке працює в tailwind.config.js

2023-08-20 17:40 UTC, ginkosoul commented on src/components/SectionTitle/SectionTitle.jsx
> +      className={`text-center mb-[16px] md:mb-[36px] ${className}
+

2023-08-21 07:04 UTC, BogdanGlazkov commented on src/app/[locale]/globals.css
> +  --arrow-image: url('../../../public/icons/arrow-down.svg');
svg не відображається. Спробуй такий шлях у файлі config: 
content: {
        'arrow-down': 'url(../../../public/icons/arrow-down.svg)',
      },

2023-08-21 14:41 UTC, nadiakhoptiuk approved these changes

2023-08-21 14:43 UTC, merged