Feature/contacts corrected
SoftRyzen-internship/ambidexter pull request #13
Opened 2023-08-18 19:43 UTC by melyasanya

2023-08-19 12:55 UTC, BogdanGlazkov approved these changes
Good

2023-08-19 13:19 UTC, BogdanGlazkov commented
Замість іконок внеси компонент SocialMedia

2023-08-19 13:25 UTC, melyasanya commented
> Замість іконок внеси компонент SocialMedia

Не впевнений чи зрозумів правильно, треба іконки тг, вайберу та вотсапу винести в окремий компонент?

2023-08-19 13:27 UTC, BogdanGlazkov commented
> > Замість іконок внеси компонент SocialMedia
> 
> Не впевнений чи зрозумів правильно, треба іконки тг, вайберу та вотсапу винести в окремий компонент?

Сорі, все ок. Там інші соцмережі

2023-08-20 08:00 UTC, nadiakhoptiuk requested changes

2023-08-20 08:00 UTC, nadiakhoptiuk commented on src/components/Contacts/Contacts.jsx
> +          <Link
Link from 'next/link' використовується для переходів між сторінками самого сайту. 
для зовнішніх посилань ми продовжуємо використовувати тег `<a>`, тут скрізь вони і будуть

2023-08-20 08:00 UTC, nadiakhoptiuk commented on src/components/Contacts/Contacts.jsx
> +              <svg
свг краще вставляти як компоненти, використовуючи svgr/webpack.
У Олега на гілці є налаштування для пакету

2023-08-21 08:24 UTC, nadiakhoptiuk requested changes

2023-08-21 08:24 UTC, nadiakhoptiuk commented on package.json
> +    "@svgr/webpack": "^8.1.0",
у залежності розробки встановити

2023-08-21 08:24 UTC, nadiakhoptiuk commented on src/components/Contacts/Contacts.jsx
> +              href="https://t.me/+380680619457"
також в ідеалі мепнути, попередньо винести у json дані і aria-labels (aria-label="посилання на Telegram" на укр)

2023-08-22 06:51 UTC, BogdanGlazkov approved these changes
Ok

2023-08-22 07:59 UTC, nadiakhoptiuk requested changes

2023-08-22 07:59 UTC, nadiakhoptiuk commented on src/components/Contacts/Contacts.jsx
> +export const Contacts = ({ data }) => {
PropTypes додати

2023-08-22 07:59 UTC, nadiakhoptiuk commented on dictionaries/en.json
> +    {"name": "Telegram", "link":"https://t.me/+380680619457", "ariaLabel":"посилання на Telegram"},
"ariaLabel" мусить бути англійською мовою тут

2023-08-22 09:07 UTC, BogdanGlazkov approved these changes

2023-08-22 09:55 UTC, nadiakhoptiuk approved these changes

2023-08-22 10:00 UTC, merged