social media component
SoftRyzen-internship/ambidexter pull request #14
Opened 2023-08-19 10:56 UTC by melyasanya

Колір в компоненті змінюється при передачі строки "menu", "hero" або будь-якої іншої, в нашому випадку "footer" в якості пропса. Можна зробити окремим файлом об'єкт з ключами та значеннями можливих пропсів, але я не впевнений куди додати цей об'єкт.

2023-08-19 13:15 UTC, BogdanGlazkov approved these changes
Good

2023-08-19 14:06 UTC, ginkosoul commented on src/components/SocialMedia/SocialMedia.jsx
> +          section === 'menu' || section === 'hero'
Можна винести в змінну (const isMenuStyle = section === 'menu' || section === 'hero')

2023-08-19 14:09 UTC, ginkosoul commented on src/components/SocialMedia/SocialMedia.jsx
> +            : `${circleClassesForAllSections} hover:bg-white focus:bg-white`
Форматований рядок більше ресурсів використає, ніж дві окремих змінних, тим більше код повторюється

2023-08-19 14:24 UTC, ginkosoul commented on src/components/SocialMedia/SocialMedia.jsx
> +              d="M2 12.7074V11.2924C2 8.39739 2 6.94939 2.905 6.01839C3.811 5.08639 5.237 5.04639 8.088 4.96539C9.438 4.92739 10.818 4.90039 12 4.90039C13.181 4.90039 14.561 4.92739 15.912 4.96539C18
Взагалі такі речі краще імпортувати:
import {ReactComponent as ReactLogo} from './logo.svg';
Нам ніби дозволили використовувати SVGR з webpack'a.
Якщо вже дуже потрібно таким чином, то кожна іконка окремий файл...

2023-08-19 15:26 UTC, melyasanya commented on src/components/SocialMedia/SocialMedia.jsx
> +            : `${circleClassesForAllSections} hover:bg-white focus:bg-white`
це можна буде зробити

2023-08-19 15:27 UTC, melyasanya commented on src/components/SocialMedia/SocialMedia.jsx
> +              d="M2 12.7074V11.2924C2 8.39739 2 6.94939 2.905 6.01839C3.811 5.08639 5.237 5.04639 8.088 4.96539C9.438 4.92739 10.818 4.90039 12 4.90039C13.181 4.90039 14.561 4.92739 15.912 4.96539C18
я запитав під час ревью, сказали поки так лишити

2023-08-20 07:27 UTC, ginkosoul commented on src/components/SocialMedia/SocialMedia.jsx
> +            : `${circleClassesForAllSections} hover:bg-white focus:bg-white`
Невдало описав... повторення коду:
section === 'menu' || section === 'hero'
            ? `${circleClassesForAllSections} hover:bg-accent focus:bg-accent`
            : `${circleClassesForAllSections} hover:bg-white focus:bg-white`
 Тут краще одну змінну:
 const circleClassName = section === 'menu' || section === 'hero'
            ? `${circleClassesForAllSections} hover:bg-accent focus:bg-accent`
            : `${circleClassesForAllSections} hover:bg-white focus:bg-white`

2023-08-20 08:20 UTC, nadiakhoptiuk requested changes

2023-08-20 08:20 UTC, nadiakhoptiuk commented on src/components/SocialMedia/SocialMedia.jsx
> +  const circleClassesForAllSections =
краще перенести, створити клас у global.css, тоді і застосовувати буде простіше, без шаблонних рядків

2023-08-20 08:20 UTC, nadiakhoptiuk commented on src/components/SocialMedia/SocialMedia.jsx
> +            : `${circleClassesForAllSections} hover:bg-white focus:bg-white`
дуже по різному можна реалізувати.

як варіант, найбільш читабельний:
`className={
          circleClassName
            ? 'circleSocialItems hover:bg-accent focus:bg-accent'
            : 'circleSocialItems hover:bg-white focus:bg-white'
        }`
        
        де circleSocialItems - клас, винесений в globals.css зі змінної circleClassesForAllSections

2023-08-20 08:20 UTC, nadiakhoptiuk commented on src/components/SocialMedia/SocialMedia.jsx
> +          <svg
краще вставляти як компоненти, через svgr/webpack (писала іншим також)

2023-08-20 08:20 UTC, nadiakhoptiuk commented on src/components/SocialMedia/SocialMedia.jsx
> +          aria-label="Instagram icon"
додати клас на посилання і розтягнути його на всю іконку (на фон), щоб при табуляції/наведенні була інтерактивна уся іконка, а не ось так:
https://prnt.sc/achcunviz6ch

2023-08-21 08:17 UTC, nadiakhoptiuk requested changes

2023-08-21 08:17 UTC, nadiakhoptiuk commented on package.json
> +    "@svgr/webpack": "^8.1.0",
в залежності розробки потрібно поставити

2023-08-21 08:17 UTC, nadiakhoptiuk commented on src/components/SocialMedia/SocialMedia.jsx
> +          className="w-full h-full flex justify-center items-center"
тут ще можна додати border-radius 50%

2023-08-21 08:17 UTC, nadiakhoptiuk commented on src/components/SocialMedia/SocialMedia.jsx
> +          href="https://www.instagram.com/ambidexter.school/"
в ідеалі - посилання і aria-labels винести в масив у словники, і мепнути його.

а іконки діставати або з об'єкта, який винести вгору компонента, або з функції-утиліти

2023-08-22 07:14 UTC, BogdanGlazkov requested changes

2023-08-22 07:14 UTC, BogdanGlazkov commented on src/components/SocialMedia/SocialMedia.jsx
> +  data: PropTypes.shape({
Поправити  data - додати arrayOf

2023-08-22 07:14 UTC, BogdanGlazkov commented on src/app/[locale]/globals.css
>  }
Здається втратив закриваючу дужку

2023-08-22 08:11 UTC, nadiakhoptiuk requested changes

2023-08-22 08:11 UTC, nadiakhoptiuk commented on src/app/[locale]/globals.css
> +@layer components {
тут помилка падає, не закрита дужка в самому низу

2023-08-22 09:30 UTC, BogdanGlazkov requested changes

2023-08-22 09:30 UTC, BogdanGlazkov commented on src/components/SocialMedia/SocialMedia.jsx
>      ariaLabel: PropTypes.string.isRequired,
В консолі помилка з Проптайпсами, виправ будь-ласка

2023-08-22 09:46 UTC, BogdanGlazkov approved these changes

2023-08-22 09:53 UTC, nadiakhoptiuk approved these changes

2023-08-22 09:53 UTC, merged