added youtube videoplayer
SoftRyzen-internship/ambidexter pull request #15
Opened 2023-08-19 12:28 UTC by ginkosoul

2023-08-19 13:08 UTC, BogdanGlazkov requested changes

2023-08-19 13:08 UTC, BogdanGlazkov commented on src/components/VideoPlayer/VideoPlayer.jsx
> +import { useState } from 'react';
Впорядкувати іморти: після 'use client' відступ, далі першим йде реакт

2023-08-19 13:08 UTC, BogdanGlazkov commented on src/components/VideoPlayer/VideoPlayer.jsx
> +        } border-accent border rounded-[10px] relative w-full md:w-[calc(50%-10px)] h-[calc(((min(100vw,480px)-40px)/280)*191)] md:h-[227px] xl:h-[428px] overflow-hidden`}
rounded-10

2023-08-19 13:08 UTC, BogdanGlazkov commented on src/components/VideoPlayer/VideoPlayer.jsx
> +            // height="480"
Консолі та коменти прибрати

2023-08-19 13:08 UTC, BogdanGlazkov commented on src/components/VideoPlayer/VideoPlayer.jsx
> +          onClick={e => {
Винести в окрему функцію

2023-08-19 13:08 UTC, BogdanGlazkov commented on src/components/VideoPlayer/VideoPlayer.jsx
> +  return (
Перед return треба відступ

2023-08-19 13:56 UTC, ginkosoul commented on src/components/VideoPlayer/VideoPlayer.jsx
> +import { useState } from 'react';
+

2023-08-19 13:56 UTC, ginkosoul commented on src/components/VideoPlayer/VideoPlayer.jsx
> +        } border-accent border rounded-[10px] relative w-full md:w-[calc(50%-10px)] h-[calc(((min(100vw,480px)-40px)/280)*191)] md:h-[227px] xl:h-[428px] overflow-hidden`}
+

2023-08-19 13:56 UTC, ginkosoul commented on src/components/VideoPlayer/VideoPlayer.jsx
> +            // height="480"
+

2023-08-19 13:56 UTC, ginkosoul commented on src/components/VideoPlayer/VideoPlayer.jsx
> +          onClick={e => {
+

2023-08-19 13:56 UTC, ginkosoul commented on src/components/VideoPlayer/VideoPlayer.jsx
> +  return (
+

2023-08-19 16:50 UTC, BogdanGlazkov approved these changes
Ok

2023-08-20 08:31 UTC, nadiakhoptiuk requested changes

2023-08-20 08:31 UTC, nadiakhoptiuk commented on src/components/VideoPlayer/VideoPlayer.jsx
> +function onStart(event, clb) {
ця функція повинна знаходитись всередині компонента, перед return
можна написати callback для кращого сприйняття

2023-08-20 08:31 UTC, nadiakhoptiuk commented on src/components/VideoPlayer/VideoPlayer.jsx
> +    event.target.classList.add('hidden');
якщо замовник бачить саме так (білий квадрат замість відео), тоді потрібно його також спробувати повернути після завершення відтвеорення. 
ну це на потім

2023-08-20 18:11 UTC, ginkosoul commented on src/components/VideoPlayer/VideoPlayer.jsx
> +function onStart(event, clb) {
+

2023-08-20 18:11 UTC, ginkosoul commented on src/components/VideoPlayer/VideoPlayer.jsx
> +    event.target.classList.add('hidden');
+

2023-08-21 07:54 UTC, nadiakhoptiuk approved these changes

2023-08-21 07:54 UTC, nadiakhoptiuk commented on src/components/VideoPlayer/VideoPlayer.jsx
> +function onStart(event, clb) {
тут ще поправити і я злию

2023-08-21 07:54 UTC, merged