Feature/btn show more
SoftRyzen-internship/ambidexter pull request #17
Opened 2023-08-19 17:54 UTC by OleksiiMatveichuk

2023-08-19 19:31 UTC, BogdanGlazkov requested changes

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/app/[locale]/globals.css
> +}
Клас mainText видалено і ці стилі перейшли на body, підтягни останні зміни

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/app/[locale]/page.jsx
>      </>
Краще передавати не весь словник, а тільки необхідну секцію localeData.courses

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/components/BtnShowMore/BtnShowMore.jsx
> +      target="_blank"
target="_blank" не треба, якщо це не зовнішнє посилання ми відкриваємо стрінку у цьому ж вікні

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/components/BtnShowMore/BtnShowMore.jsx
> +      className="flex items-center justify-center bg-bgColor text-black hover:bg-white p-4 rounded-[10px] text-middle min-w-full xl:text-large duration-300 xl:px-20 xl:min-w-max"
Використовуй rounded-10 з конфіг файла
Текст по замовчуванню text-black, можна це не вказувати
Де hover, там і focus (аналогічний)
Задати font-weight
Задати розміри за макетом

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/components/CoursesCard/CoursesCard.jsx
> +import Image from 'next/image';
Впорядкуй імпорти, спочатку зовнішні, потім через відступ внутрішні

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/sections/Courses/Courses.jsx
> +
Впорядкувати імпорти, внутрішні разом

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/components/CoursesCard/CoursesCard.jsx
> +      <Image
rounded-10
На десктопі картинки мають бути більше

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/sections/Courses/Courses.jsx
> +    { img: actorImg, link: routes.ACTING_SKILL },
Змінній краще дати описову назву: imageArray

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/sections/Courses/Courses.jsx
> +
Змінним краще давати описові назви, щоб інші могли розуміти, що там знаходиться. Напр. image, card, index

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/sections/Courses/Courses.jsx
> +    >
Фігурні дужки не треба

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/sections/Courses/Courses.jsx
> +            <li className="w-full" key={i}>
Змінним описові назви

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/components/CoursesCard/CoursesCard.jsx
> +      />
Просто Аuthor. Зрозуміло що це картинка, не треба це писати в alt

2023-08-19 19:31 UTC, BogdanGlazkov commented on src/sections/Courses/Courses.jsx
> +          {subTitle}
Марджин топ забрати, там буде нижній відступ у компонента SectionTitle

2023-08-19 20:29 UTC, ginkosoul commented on src/sections/Courses/Courses.jsx
> +    >
Дужки потрібні для форматованого рядка... саме форматований рядок тут не потрібен... зайві операції не портібні... дужки прибираємо, лапки міняємо

2023-08-20 08:59 UTC, nadiakhoptiuk requested changes

2023-08-20 08:59 UTC, nadiakhoptiuk commented on src/app/[locale]/page.jsx
>      </>
а ще краще деструктуризувати вгорі компонента сторінки на окремі обєкти

2023-08-20 08:59 UTC, nadiakhoptiuk commented on src/components/BtnShowMore/BtnShowMore.jsx
> +      target="_blank"
в даному випадку ми використовуємо Link від next для переходу між сторінками сайту, а не тег посилання

2023-08-20 08:59 UTC, nadiakhoptiuk commented on src/components/CoursesCard/CoursesCard.jsx
> +    img: PropTypes.shape.isRequired,
https://prnt.sc/gYpxGBony-Uv

2023-08-20 08:59 UTC, nadiakhoptiuk commented on src/components/CoursesCard/CoursesCard.jsx
> +      />
насправді, альт має якомога точніше описувати картинку, в даному випадку картинки динамічні, опис також повинен бути динамічний + змінюватися в залежності від мови, 
мабуть треба виносити всі альти у json.
тоді уже і посилання на картинку можна винести туди

2023-08-20 08:59 UTC, nadiakhoptiuk commented on src/components/CoursesCard/CoursesCard.jsx
> +      />
+ питаннячко, чому в картинки білий фон, пошукайте

2023-08-20 08:59 UTC, nadiakhoptiuk commented on src/app/[locale]/globals.css
> +  --bg-courses-section: url('../../../public/images/courses-bg.png');
такі речі додаємо через конфіг тейлвінда

2023-08-20 08:59 UTC, nadiakhoptiuk commented on tailwind.config.js
> +        coursesBg: 'var(--bg-courses-section)',
тут прописати без рута з глобал, ось так
https://tailwindcss.com/docs/background-image#using-custom-values

2023-08-20 09:27 UTC, BogdanGlazkov commented on src/components/CoursesCard/CoursesCard.jsx
> +      />
Дизайнер вже надав нормальну картинку, вона на макеті вгорі

2023-08-20 10:48 UTC, ginkosoul commented on tailwind.config.js
> +        coursesBg: 'var(--bg-courses-section)',
А як 2х підключити?..

2023-08-20 12:27 UTC, OleksiiMatveichuk commented on src/app/[locale]/globals.css
> +}
+

2023-08-20 12:28 UTC, OleksiiMatveichuk commented on src/components/BtnShowMore/BtnShowMore.jsx
> +      target="_blank"
+

2023-08-20 12:29 UTC, OleksiiMatveichuk commented on src/components/CoursesCard/CoursesCard.jsx
> +import Image from 'next/image';
+

2023-08-20 12:30 UTC, OleksiiMatveichuk commented on src/sections/Courses/Courses.jsx
> +    >
+

2023-08-20 12:31 UTC, OleksiiMatveichuk commented on src/sections/Courses/Courses.jsx
> +          {subTitle}
+

2023-08-20 12:36 UTC, OleksiiMatveichuk commented on src/app/[locale]/page.jsx
>      </>
+

2023-08-20 13:40 UTC, BogdanGlazkov commented on tailwind.config.js
> +        coursesBg: 'var(--bg-courses-section)',
https://stackoverflow.com/questions/75885869/customize-tailwind-breaktpoints-for-high-resolution-and-high-ppi-screens

2023-08-20 14:59 UTC, OleksiiMatveichuk commented on src/components/BtnShowMore/BtnShowMore.jsx
> +      className="flex items-center justify-center bg-bgColor text-black hover:bg-white p-4 rounded-[10px] text-middle min-w-full xl:text-large duration-300 xl:px-20 xl:min-w-max"
+

2023-08-20 15:23 UTC, OleksiiMatveichuk commented on src/sections/Courses/Courses.jsx
> +
+

2023-08-20 15:23 UTC, OleksiiMatveichuk commented on src/sections/Courses/Courses.jsx
> +            <li className="w-full" key={i}>
+

2023-08-20 18:30 UTC, BogdanGlazkov requested changes

2023-08-20 18:30 UTC, BogdanGlazkov commented on src/sections/Courses/Courses.jsx
> +
Я про це -  el, i

2023-08-20 18:30 UTC, BogdanGlazkov commented on src/sections/Courses/Courses.jsx
> +            <li className="w-full" key={i}>
Я про ці змінні - (el, i)

2023-08-20 18:30 UTC, BogdanGlazkov commented on tailwind.config.js
>        },
Імпорт з іншої папки - url('../../../public/images/courses-bg.png')

2023-08-20 18:30 UTC, BogdanGlazkov commented on dictionaries/en.json
> +        "imageURL": "/_next/static/media/actor.c3538cda.png",
Шлях до папки public/images

2023-08-20 18:30 UTC, BogdanGlazkov commented on dictionaries/en.json
> +        "imageURL": "/_next/static/media/orator.102b2436.png",
Шлях до папки public/images

2023-08-20 19:21 UTC, OleksiiMatveichuk commented on tailwind.config.js
>        },
+

2023-08-20 19:25 UTC, OleksiiMatveichuk commented on dictionaries/en.json
> +        "imageURL": "/_next/static/media/actor.c3538cda.png",
Мені потрібна допомога. Який би шлях я не прописував, картинки не відображає. Тільки цей шлях, або імпорт іmg одразу до компоненту. Next  не хоче або я не можу. Допоможи розібратись

2023-08-21 07:10 UTC, BogdanGlazkov commented on dictionaries/en.json
> +        "imageURL": "/_next/static/media/actor.c3538cda.png",
imageURL не змінюється і не перекладається, не бачу сенсу його тут писати. Краще імпортувати картинку в компонент, як раніше

2023-08-21 09:28 UTC, OleksiiMatveichuk commented on src/sections/Courses/Courses.jsx
> +
+

2023-08-21 09:28 UTC, OleksiiMatveichuk commented on src/sections/Courses/Courses.jsx
> +            <li className="w-full" key={i}>
+

2023-08-21 09:29 UTC, OleksiiMatveichuk commented on dictionaries/en.json
> +        "imageURL": "/_next/static/media/actor.c3538cda.png",
+

2023-08-21 09:29 UTC, OleksiiMatveichuk commented on dictionaries/en.json
> +        "imageURL": "/_next/static/media/orator.102b2436.png",
+

2023-08-21 09:58 UTC, nadiakhoptiuk approved these changes

2023-08-21 10:14 UTC, BogdanGlazkov requested changes

2023-08-21 10:14 UTC, BogdanGlazkov commented on src/sections/Courses/Courses.jsx
> +    cards: PropTypes.arrayOf.isRequired,
В консолі помилка, треба розшифрувати cards

2023-08-21 10:14 UTC, BogdanGlazkov commented on src/components/CoursesCard/CoursesCard.jsx
> +    cardImg: PropTypes.objectOf.isRequired,
В консолі помилка, треба прибрати objectOf

2023-08-21 10:40 UTC, nadiakhoptiuk approved these changes

2023-08-21 10:40 UTC, merged