created section FreeClass
SoftRyzen-internship/ambidexter pull request #18
Opened 2023-08-20 10:42 UTC by ginkosoul

2023-08-20 18:04 UTC, BogdanGlazkov requested changes
Додати реекспорт та імпорт секції на головну сторінку

2023-08-20 18:04 UTC, BogdanGlazkov commented on src/sections/FreeClass/FreeClass.jsx
> +  altText: PropTypes.string,
isRequired

2023-08-20 18:04 UTC, BogdanGlazkov commented on src/sections/FreeClass/FreeClass.jsx
> +  btnLabel: PropTypes.string,
isRequired

2023-08-20 18:04 UTC, BogdanGlazkov commented on src/sections/FreeClass/FreeClass.jsx
> +            </p>
Перевір вирівнювання тексту

2023-08-20 18:04 UTC, BogdanGlazkov commented on src/sections/FreeClass/FreeClass.jsx
> +}) => {
Звідки приходять ці дані? Додати рендер секції на домашній сторінці

2023-08-20 18:04 UTC, BogdanGlazkov commented on src/sections/FreeClass/FreeClass.jsx
> +  }`;
!isCoursePage && 'xl:py-40' - це не треба, у всіх секцій однакові падінги і вони будуть задані у css файлі

2023-08-20 18:04 UTC, BogdanGlazkov commented on src/sections/FreeClass/FreeClass.jsx
> +  const imgUrl = "url('../../../public/images/free-bg.png')";
Імпорт не у global.css, а у tailwind.config, за прикладом:

extend: {
      backgroundImage: {
        format: "url('../../../public/images/format-bg-x2.png')",
      },

2023-08-21 05:53 UTC, ginkosoul commented on src/sections/FreeClass/FreeClass.jsx
> +  altText: PropTypes.string,
+

2023-08-21 05:53 UTC, ginkosoul commented on src/sections/FreeClass/FreeClass.jsx
> +  btnLabel: PropTypes.string,
+

2023-08-21 05:53 UTC, ginkosoul commented on src/sections/FreeClass/FreeClass.jsx
> +            </p>
+

2023-08-21 05:53 UTC, ginkosoul commented on src/sections/FreeClass/FreeClass.jsx
> +}) => {
+

2023-08-21 05:55 UTC, ginkosoul commented on src/sections/FreeClass/FreeClass.jsx
> +  }`;
На макеті по-іншому для цієї секції... поки залишаю так... до узгодження

2023-08-21 05:56 UTC, ginkosoul commented on src/sections/FreeClass/FreeClass.jsx
> +  const imgUrl = "url('../../../public/images/free-bg.png')";
Зробив, але працює дивно... потрібно буде переробити

2023-08-21 07:21 UTC, BogdanGlazkov requested changes

2023-08-21 07:21 UTC, BogdanGlazkov commented on src/sections/FreeClass/FreeClass.jsx
> +    <section className={sectionClasses}>
Для навігації треба додати id

2023-08-21 07:21 UTC, BogdanGlazkov commented on src/app/[locale]/page.jsx
> +import { FreeClass } from '@/sections/FreeClass/FreeClass';
import { Hero, FreeClass } from '@/sections';

2023-08-21 07:21 UTC, BogdanGlazkov commented on src/sections/FreeClass/FreeClass.jsx
> +    <section className={sectionClasses}>
id?

2023-08-21 07:23 UTC, BogdanGlazkov commented on src/sections/FreeClass/FreeClass.jsx
> +  }`;
Я задав кожній секції pb-[150px], тоді всюди буде однаково, і ця секція не відрізняється від інших

2023-08-21 15:44 UTC, nadiakhoptiuk requested changes

2023-08-21 15:44 UTC, nadiakhoptiuk commented on src/sections/FreeClass/FreeClass.jsx
> +        <div className="md:flex md:gap-5 md:items-center">
перевір gap на десктопі, має інший вид

2023-08-21 22:02 UTC, ginkosoul commented on src/sections/FreeClass/FreeClass.jsx
> +    <section className={sectionClasses}>
+

2023-08-21 22:02 UTC, ginkosoul commented on src/app/[locale]/page.jsx
> +import { FreeClass } from '@/sections/FreeClass/FreeClass';
+

2023-08-21 22:02 UTC, ginkosoul commented on src/sections/FreeClass/FreeClass.jsx
> +        <div className="md:flex md:gap-5 md:items-center">
+

2023-08-22 08:18 UTC, BogdanGlazkov approved these changes
Ок

2023-08-22 09:37 UTC, nadiakhoptiuk requested changes

2023-08-22 09:37 UTC, nadiakhoptiuk commented on public/images/free-bg-xl-x2.webp
ми не вантажимо webp, вантажимо старий добрий jpeg, png

next під капотом згенерує webp, а якщо захочемо і налаштуємо, то навіть avif)

2023-08-22 09:37 UTC, nadiakhoptiuk commented on src/sections/FreeClass/FreeClass.jsx
> +  }`;
повинно бути 160

2023-08-22 09:37 UTC, nadiakhoptiuk commented on src/sections/FreeClass/FreeClass.jsx
> +  }`;
верхні падінги прибрати, нижні або за класом, або 80 (якщо це сторінка з курсом)
фон замінимо, його розтягує/розмиває

2023-08-23 11:36 UTC, nadiakhoptiuk requested changes

2023-08-23 11:36 UTC, nadiakhoptiuk commented on src/sections/FreeClass/FreeClass.jsx
> +              <Image
картинку можна робити w-full h-auto

2023-08-23 11:36 UTC, nadiakhoptiuk commented on src/sections/FreeClass/FreeClass.jsx
> +              <p className="text-small/[1.25] md:text-middle/[1.208] xl:text-large/[1.208] font-medium text-justify md:text-left mb-4 xl:mb-6">
опис і кнопку для телефона зафіксуємо max-w-[320px] і ml-auto mr-auto

2023-08-23 16:04 UTC, nadiakhoptiuk requested changes

2023-08-23 16:04 UTC, nadiakhoptiuk commented on src/sections/FreeClass/FreeClass.jsx
> +      <div className="freeClassSection">
цей дів прибереш, фонове зображення - на секцію, і додаш градієнт як у конфігу.

2023-08-24 10:32 UTC, ginkosoul commented on src/sections/FreeClass/FreeClass.jsx
> +      <div className="freeClassSection">
+

2023-08-24 10:32 UTC, ginkosoul commented on src/sections/FreeClass/FreeClass.jsx
> +              <p className="text-small/[1.25] md:text-middle/[1.208] xl:text-large/[1.208] font-medium text-justify md:text-left mb-4 xl:mb-6">
+

2023-08-24 10:32 UTC, ginkosoul commented on src/sections/FreeClass/FreeClass.jsx
> +              <Image
+

2023-08-24 10:33 UTC, ginkosoul commented on public/images/free-bg-xl-x2.webp
png + webp

2023-08-24 11:45 UTC, nadiakhoptiuk approved these changes

2023-08-24 11:50 UTC, merged