Feature/item course
SoftRyzen-internship/ambidexter pull request #20
Opened 2023-08-20 20:07 UTC by olegvoskovets

2023-08-21 07:44 UTC, BogdanGlazkov commented
Зробити нову гілку з мерджем у dev, а цю видалити

2023-08-21 07:49 UTC, BogdanGlazkov requested changes
Ми мерджимо у dev, а не main, перероби будь-ласка)

2023-08-21 07:53 UTC, olegvoskovets commented
поправив

2023-08-21 08:34 UTC, BogdanGlazkov requested changes

2023-08-21 08:34 UTC, BogdanGlazkov commented on src/components/ItemCourse/ItemCourse.jsx
> +    return '';
Перевірку робити не обов'язково, бо є PropTypes.string.isRequired

2023-08-21 08:34 UTC, BogdanGlazkov commented on src/components/ItemCourse/ItemCourse.jsx
> +
Можна спростити const thisTitle = title.split('.');
І тоді функція вище не потрібна

2023-08-21 08:34 UTC, BogdanGlazkov commented on src/components/ItemCourse/ItemCourse.jsx
> +      <div className="text-middle xl:text-[24px] py-3 md:py-4 bg-accent text-center font-medium ">
rounded-10 (цей клас є у конфіг файлі)

2023-08-21 08:34 UTC, BogdanGlazkov commented on tailwind.config.js
> +    },
Краще назвати acent по аналогії

2023-08-21 08:34 UTC, BogdanGlazkov commented on src/components/ItemCourse/ItemCourse.jsx
> +export const ItemCourse = ({ data }) => {
Це картка, тому краще назвати ItemCourseCard

2023-08-21 08:34 UTC, BogdanGlazkov commented on src/components/ItemCourse/ItemCourse.jsx
> +            >
text-list що дає?

2023-08-21 08:34 UTC, BogdanGlazkov commented on src/components/ItemCourse/ItemCourse.jsx
> +            >
Там є нижній відступ після кожного пункту

2023-08-21 08:34 UTC, BogdanGlazkov commented on src/components/ItemCourse/ItemCourse.jsx
> +        <ul>
На макеті на мобілці ширина менше, на таблеті більше

2023-08-21 08:34 UTC, BogdanGlazkov commented on src/components/ItemCourse/ItemCourse.jsx
> +
Крапки зникають, тоді навіщо взагалі ця функція? Краще задати потрібну ширину заголовку

2023-08-21 08:56 UTC, olegvoskovets commented on src/components/ItemCourse/ItemCourse.jsx
> +export const ItemCourse = ({ data }) => {
поправив

2023-08-21 09:22 UTC, olegvoskovets commented on src/components/ItemCourse/ItemCourse.jsx
> +      <div className="text-middle xl:text-[24px] py-3 md:py-4 bg-accent text-center font-medium ">
поправив

2023-08-21 09:23 UTC, olegvoskovets commented on src/components/ItemCourse/ItemCourse.jsx
> +
Там кожне речення з нової строки

2023-08-21 09:27 UTC, olegvoskovets commented on tailwind.config.js
> +    },
acent

2023-08-21 09:27 UTC, olegvoskovets commented on src/components/ItemCourse/ItemCourse.jsx
> +            >
видалив

2023-08-21 09:50 UTC, BogdanGlazkov commented on tailwind.config.js
> +    },
*accent

2023-08-21 09:51 UTC, BogdanGlazkov commented on src/components/ItemCourse/ItemCourse.jsx
> +
Можна зробити щось таке:
title = title.replace('. ', '.\n');
\n це перенос строки

2023-08-21 11:58 UTC, olegvoskovets commented on src/components/ItemCourse/ItemCourse.jsx
> +
не хоче вірно працювати. поки залишив функцію

2023-08-21 12:01 UTC, olegvoskovets commented on src/components/ItemCourse/ItemCourse.jsx
> +        <ul>
до 480 тягнеться

2023-08-21 13:04 UTC, BogdanGlazkov requested changes

2023-08-21 13:04 UTC, BogdanGlazkov commented on src/components/ItemCourseCard/ItemCourseCard.jsx
> +    <div className="box-border  w-full md:w-[334px] xl:w-[630px]  border-2 border-acent rounded-10">
*border-accent

2023-08-21 13:04 UTC, BogdanGlazkov commented on src/components/ItemCourse/ItemCourse.jsx
> +        <ul>
Так, тягнеться до 480, а в тебе до 768

2023-08-21 13:04 UTC, BogdanGlazkov commented on src/components/ItemCourse/ItemCourse.jsx
> +            >
Там треба нижній відступ після кожного пункту - не зроблено

2023-08-21 13:04 UTC, BogdanGlazkov commented on src/components/ItemCourseCard/ItemCourseCard.jsx
> +      <div className="p-3 md:px-6 xl:py-6 text-small xl:text-middle">
md:px-6 - по факту він менше, бо на макеті текст та крапки виходять на падінг

2023-08-21 13:04 UTC, BogdanGlazkov commented on src/components/ItemCourseCard/ItemCourseCard.jsx
> +            <li key={i}>{item}. </li>
Мистецтво аргументації. Як переконувати.
Відстоювати свою точку зору. - цей текст на десктопі має бути у 2 строки. Треба подумати як це реалізувати

2023-08-21 13:11 UTC, nadiakhoptiuk commented on src/components/ItemCourse/ItemCourse.jsx
> +
` const titleSplit = title => {
    const text = title.split('.');
    text.pop();
    return text;
  };`
  
  
  `<h3>
          {!title.includes('.') ? (
            <span>{title}</span>
          ) : (
            title.includes('.') &&
            titleSplit(title).map((item, i) => (
              <span key={i} className="block">
                {item}.
              </span>
            ))
          )}
        </h3>`

2023-08-21 13:59 UTC, olegvoskovets commented on src/components/ItemCourseCard/ItemCourseCard.jsx
> +            <li key={i}>{item}. </li>
Надя і в цьому коді знайшла помилку і показала

2023-08-21 18:36 UTC, BogdanGlazkov commented on src/components/ItemCourseCard/ItemCourseCard.jsx
react завжди йде першим, prop-types в кінці, бо використовується в кінці сторінки

2023-08-21 18:36 UTC, BogdanGlazkov commented on src/components/ItemCourseCard/ItemCourseCard.jsx
> +
Desktop

2023-08-21 18:36 UTC, BogdanGlazkov commented on src/components/ItemCourseCard/ItemCourseCard.jsx
> +  const decktop = useMediaQuery({ minWidth: 1440 });
desktop

2023-08-21 18:36 UTC, BogdanGlazkov commented on src/components/ItemCourseCard/ItemCourseCard.jsx
> +      const titleDecktop = [];
titleDesktop

2023-08-21 18:36 UTC, BogdanGlazkov commented on src/components/ItemCourseCard/ItemCourseCard.jsx
>    }),
data теж isRequired

2023-08-21 18:36 UTC, BogdanGlazkov commented on src/components/ItemCourseCard/ItemCourseCard.jsx
> +    <div className="box-border  w-full md:w-[334px] xl:w-[630px]  border-2 border-acent rounded-10">
box-border - ця властивість встановлена за замовчуванням, повторно писати не треба

2023-08-21 18:46 UTC, BogdanGlazkov requested changes

2023-08-21 18:46 UTC, BogdanGlazkov commented on src/components/ItemCourseCard/ItemCourseCard.jsx
>        <div className="text-middle xl:text-[24px] py-3 md:py-4 bg-accent text-center font-medium ">
На макеті line-height менший (спробуй leading-tight)

2023-08-21 18:46 UTC, BogdanGlazkov commented on src/components/ItemCourseCard/ItemCourseCard.jsx
>              >
Тут теж leading-tight

2023-08-22 08:16 UTC, nadiakhoptiuk requested changes

2023-08-22 08:16 UTC, nadiakhoptiuk commented on src/components/ItemCourseCard/ItemCourseCard.jsx
> +            title.includes('.') &&
тут розібратися, якщо це тернарник, то не потрібно амперсанд в другій частині

2023-08-22 15:53 UTC, BogdanGlazkov approved these changes

2023-08-22 18:29 UTC, BogdanGlazkov approved these changes

2023-08-22 18:29 UTC, BogdanGlazkov commented on tailwind.config.js
Це не треба видаляти)

2023-08-22 18:29 UTC, BogdanGlazkov commented on src/app/[locale]/globals.css
Це теж не треба видаляти)

2023-08-23 07:40 UTC, nadiakhoptiuk approved these changes

2023-08-23 07:42 UTC, merged