Feature/feedback form
SoftRyzen-internship/ambidexter pull request #21
Opened 2023-08-21 15:45 UTC by melyasanya

Цей коміт чомусь вийшов в перемішку зі стягненнями, які я зробив з деву. Мої зміни це 3 компоненти: Feedback, Incorrect, NotificationForm, функція sendMessageTelegram в утілах, класси в глобал css, іконки та пакети. Також в мене відразу є запитання стосовно .env файлу. Я його створив, записав туди ключ, використав дотенв, але все одного не можу побачити ключ. Може є якась специфіка роботи з .env файлом на нексті?

2023-08-21 19:48 UTC, BogdanGlazkov commented
Спробуй перейменувати файл у .env.local (і відповідно .env.local.example)

2023-08-22 06:11 UTC, ginkosoul commented on src/components/NotificationForm/NotificationForm.jsx
> +          : 'Виникла помилка при відправленні!'}
Тексти, які мають(матимуть) переклад винести в .json

2023-08-22 06:16 UTC, ginkosoul commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      subject: localStorage.getItem('subject'),
Не впевнений, але, мабуть краще страхуватися:
subject: localStorage.getItem('subject') || "",

2023-08-22 06:19 UTC, ginkosoul commented on package.json
> +    "dotenv": "^16.3.1",
Наскільки мені відомо це зайве у Next

2023-08-22 06:25 UTC, ginkosoul commented on src/components/FeedbackForm/FeedbackForm.jsx
> +              pattern: /^(?!-)[A-Za-z0-9._-]+@[-A-Za-z0-9]+\.[A-Za-z]{2,}$/,
Краще винести у змінну і окремим файлом... хоча б у змінну... зразу після імпортів... я б взагалі використав yup для валідації...

2023-08-22 06:26 UTC, ginkosoul commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          value="Відправити"
Тексти, які мають(матимуть) переклад винести в .json

2023-08-22 07:08 UTC, ginkosoul commented on src/layout/Header/Header.jsx
> +  const [isOpen, setIsOpen] = useState(false);
Що це?.. для прикладу?.. "use client" тут зайвий... краще логіку переносити в самий низ(на кнопку)... тут чудово підійде кастомний хук... тоді логіка залишиться тільки на кнопках і на модалці... гляньте конспект по react (custom hook) там є чудовий приклад...

2023-08-22 07:51 UTC, BogdanGlazkov commented on package.json
> +    "dotenv": "^16.3.1",
Так, тут ми маємо доступ без dotenv напряму, через process.env

2023-08-22 07:52 UTC, BogdanGlazkov commented on package.json
> +    "dotenv": "^16.3.1",
Але якщо це use client компонент, там назва змінної повинна називатися трохи по-іншому

2023-08-22 08:06 UTC, BogdanGlazkov requested changes

2023-08-22 08:06 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +
Цей пакет не треба. Назви env змінних у клієнтському компоненті мають починатися з NEXT_PUBLIC_

2023-08-22 08:06 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +            ПІБ <span className="text-red">*</span>
Взяти текст з json файла

2023-08-22 08:06 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          {errors.name && <IncorrectForm text={'Невірний ПІБ'} />}
Взяти текст з json файла

2023-08-22 08:06 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +            placeholder="Іванов Іван Іванович"
Взяти текст з json файла

2023-08-22 08:06 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +            Номер телефону <span className="text-red">*</span>
Взяти текст з json файла

2023-08-22 08:06 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          Повідомлення
Взяти текст з json файла

2023-08-22 08:06 UTC, BogdanGlazkov commented on src/utils/sendMessageTelegram.js
> +  const token = '6300072134:AAG2uT731m-XLcCZNaxfvOpXIDWY6bB8F0U';
Винести в env файл

2023-08-22 08:06 UTC, BogdanGlazkov commented on src/utils/sendMessageTelegram.js
> +  const url = `https://api.telegram.org/bot${token}/sendMessage?chat_id=${chatId}`;
Винести в env файл

2023-08-22 09:15 UTC, nadiakhoptiuk commented
> 

dotenv не потрібен для некста, звернення до змінних: process.env.NEXT_PUBLIC_...
змінні називай NEXT_PUBLIC_... щоб були доступні в браузерному середовищі

env.local на продакшені наче не працюють, ми завжди використовували .env

2023-08-22 09:33 UTC, nadiakhoptiuk commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      subject: localStorage.getItem('subject'),
https://prnt.sc/w5T5VBUDLqSR

2023-08-22 10:15 UTC, nadiakhoptiuk requested changes

2023-08-22 10:15 UTC, nadiakhoptiuk commented on src/app/[locale]/globals.css
> +  }
все чудово, тільки закрити дужку в кінці (внизу)

2023-08-22 10:15 UTC, nadiakhoptiuk commented on src/components/FeedbackForm/FeedbackForm.jsx
> +        <button
краще зробити 2 окремі компоненти: модалка і форма. кнопку закриття модалки помістити в модалку, а не всередину форми відповідно

кнопку зробити більшою (40х40), іконку не міняти, відцентрувати

2023-08-22 10:15 UTC, nadiakhoptiuk commented on src/components/FeedbackForm/FeedbackForm.jsx
> +        <input
зробити кнопку для відправки форми, додати на неї курсор поінтер, ховери/фокуси

2023-08-22 10:15 UTC, nadiakhoptiuk commented on src/components/FeedbackForm/FeedbackForm.jsx
> +    sendMessageTelegram(data);
https://prnt.sc/iKYzCHwrZ2Hx

тут показувати треба повідомлення знизу тільки якщо валідація ок, а відправка на сервер викликала помилку.
тобто обгорнути в try catch, і якщо все ок, тоді ми чистимо форму і показуємо успішне повідомлення.

якщо ж помилка, форму не чистимо, показуємо помилку під кнопкою

2023-08-22 10:15 UTC, nadiakhoptiuk commented on src/components/FeedbackForm/FeedbackForm.jsx
> +  };
форма не чиститься під час відправки, якщо успіх
https://prnt.sc/w2PGmqY7__OJ

2023-08-22 18:36 UTC, melyasanya commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      subject: localStorage.getItem('subject'),
Я не дуже зрозумів, в чому саме проблема, бо я скрін не можу відкрити. Наскільки я зрозумів, то в локалсторіджі потрібно створювати ключі, коли щось вже є заповнене в інпуті. Коли локалсторедж пустий і воно в дефолт немає чого записувати, то помилки воно не видає, я перевіряв, воно просто нічого не записує, як і повинно бути. Я поки поставив варіант, який Віталік запропонував, але особисто в мене воно нічого не змінює.

2023-08-22 20:16 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      subject: localStorage.getItem('subject'),
На скріншоті скрін помилки ReferenceError: localStorage is not defined

2023-08-22 20:24 UTC, melyasanya commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      subject: localStorage.getItem('subject'),
дивно, в мене не видає чомусь помилки, хоча я перевіряю сторедж, там пусто

2023-08-23 08:25 UTC, BogdanGlazkov requested changes

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +'use client';
Відступ

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +import { NotificationForm } from '../NotificationForm/NotificationForm';
from '..';

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +import { IncorrectForm } from '../IncorrectForm/IncorrectForm';
from '..';

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      className="flex flex-col border border-accent rounded-[10px] bg-white w-[280px] mx-auto px-[12px] pb-[64px] pt-[56px] md:w-[452px] md:px-[24px] md:pt-[56px] xl:w-[844px] xl:px-[48px] xl:pt-[108
Замість rounded-[10px] використовуємо rounded-10 з конфіг файлу

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      </div>
Між інпутами додати відступи для читабельності

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      <div className=" relative flex flex-col">
div не потрібен, можна все обгорнути в label, і тоді не треба htmlFor

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      <div className=" relative flex flex-col">
div не потрібен, можна все обгорнути в label, і тоді не треба htmlFor

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          placeholder="+38 (097) 12 34 567 0"
Це  placeholder з помилкою, 0 треба прибрати

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      <div className=" relative flex flex-col">
Відступ
Огорнути в label

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      <label htmlFor="subject" className="formLabel">
Відступ
Огорнути в label

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +        className="mb-[24px] h-[146px] border rounded-[10px] border-accent px-[12px] py-[8px] leading-[1.15] placeholder:text-black placeholder:opacity-50 placeholder:text-base placeholder:font-norma
rounded-10

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +        className="bg-accent rounded-[10px] py-[8px] text-middle font-medium max-h-[35px] xl:max-h-[76px] xl:py-[16px] xl:text-large36 flex justify-center items-center hover:bg-white hover:border-[2p
rounded-10

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/app/[locale]/globals.css
> +    @apply mb-[12px] border rounded-[10px]  px-[12px] py-[8px] leading-[1.15] placeholder:opacity-50  placeholder:text-base placeholder:font-normal xl:px-[24px] xl:py-[16px] xl:placeholder:text-large
rounded-10

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/index.js
>  export * from './VideoPlayer/VideoPlayer';
Додати ModalForm

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/ModalForm/ModalForm.jsx
> +  };
Відступ перед  return

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/ModalForm/ModalForm.jsx
> +      className="bg-bgColor pt-[24px] h-full w-full z-10 "
Може краще z-30, щоб перекривало header, hero та все інше?

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +'use client';
Відступ

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +import { useState } from 'react';
react йде першим

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +import { ModalForm } from '@/components/ModalForm/ModalForm';
Перенести у об'єкт до інших компонентів

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +
А навіщо викликати модалку в хедері, якщо ми викликаємо її в кнопці ApplyButton?

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +import { Container, FeedbackForm, LocaleSwitcher, Logo } from '@/components';
FeedbackForm тут не використовується

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          ПІБ <span className="text-red">*</span>
В макеті були зміни, зараз там Імʼя *

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          placeholder="Іванов Іван Іванович"
Зараз там просто Іван)

2023-08-23 08:25 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          placeholder="yourmail-mail.com"
А де собачка?)

2023-08-23 08:28 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      subject: localStorage.getItem('subject'),
Знов помилка: error ReferenceError: localStorage is not defined
Спробуй localStorage?.getItem('subject') || "",

2023-08-23 19:19 UTC, BogdanGlazkov requested changes
На десктопі модалка виходить за межі екрана, не видно верх форми, низ, і не скролиться. Треба пофіксити

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/app/[locale]/globals.css
> +  }
max-md:mb-3 тут баг, треба max- прибрати, бо код не запускається.

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +import { NotificationForm } from '../NotificationForm/NotificationForm';
import { IncorrectForm,  NotificationForm, Loader } from '..';

2023-08-23 19:19 UTC, BogdanGlazkov commented on dictionaries/uk.json
> +      "errors": ["Невірнe ПІБ"]
"Невірнe Ім'я"

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/ApplyButton/ApplyButton.jsx
> +import { useState } from 'react';
react йде першим у всіх імпортах

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/ApplyButton/ApplyButton.jsx
> +    }),
shape це об'єкт, він також обов'язковий (isRequired)

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/ApplyButton/ApplyButton.jsx
> +    }),
isRequired

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/ApplyButton/ApplyButton.jsx
> +    }),
isRequired

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/ApplyButton/ApplyButton.jsx
> +    }),
isRequired

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/ApplyButton/ApplyButton.jsx
> +    }),
isRequired

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/ApplyButton/ApplyButton.jsx
> +  }),
Об'єкт  formData isRequired

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/ApplyButton/ApplyButton.jsx
>    return (
Відступ перед return

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          className="mb-[24px] h-[146px] border rounded-10 border-accent px-[12px] py-[8px] leading-[1.15] placeholder:text-black placeholder:opacity-50 placeholder:text-base placeholder:font-normal
font-size: 14px;
Заборонити resize! resize-none

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          />
При помилці набраний текст також має бути червоний

2023-08-23 19:19 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          className="bg-accent rounded-10 py-[8px] text-middle font-medium max-h-[35px] xl:max-h-[76px] xl:py-[16px] xl:text-large36 flex justify-center items-center hover:bg-white hover:border-[2px]
Де hover, там і focus (такий самий)

2023-08-23 19:21 UTC, BogdanGlazkov commented
І ще у консолі помилка ReferenceError: Cannot access 'ApplyButton' before initialization
Цей компонент викликається до його ініціалізації, треба пошукати де саме

2023-08-23 20:50 UTC, melyasanya commented
> І ще у консолі помилка ReferenceError: Cannot access 'ApplyButton' before initialization Цей компонент викликається до його ініціалізації, треба пошукати де саме

Відправив виправлену версію, але це я взагалі не знаю як фіксити. Цей компонент не мій, але час від час така сама помилка вистрибує на компоненти modal та feedback і я не розумію через що вона з'являється

2023-08-24 07:40 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +import { NotificationForm } from '../NotificationForm/NotificationForm';
Loader забув

2023-08-24 07:45 UTC, melyasanya commented on src/components/FeedbackForm/FeedbackForm.jsx
> +import { NotificationForm } from '../NotificationForm/NotificationForm';
> Loader забув

додав

2023-08-24 07:47 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          className="mb-[24px] h-[146px] border rounded-10 border-accent px-[12px] py-[8px] leading-[1.15] placeholder:text-black placeholder:opacity-50 placeholder:text-base placeholder:font-normal
font-size: 14px; - не виправлено

2023-08-24 07:55 UTC, melyasanya commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          className="mb-[24px] h-[146px] border rounded-10 border-accent px-[12px] py-[8px] leading-[1.15] placeholder:text-black placeholder:opacity-50 placeholder:text-base placeholder:font-normal
> font-size: 14px; - не виправлено

вже виправив

2023-08-24 08:05 UTC, BogdanGlazkov requested changes
Думаю не варто жорстко прив'язувати модалку до форми. Краще зробити модалку універсальною, а форму прокидати в неї як children

2023-08-24 08:05 UTC, BogdanGlazkov commented on src/components/ModalForm/ModalForm.jsx
> +import { Dialog } from '@headlessui/react';
Відступ між зовнішніми та внутрішніми імпортами

2023-08-24 08:05 UTC, BogdanGlazkov commented on src/components/ModalForm/ModalForm.jsx
> +              </button>
Якщо кнопка містить іконку, але немає тексту, треба додати aria-label для доступності (скрін-рідери і т.д.). У даному випадку додати в файл json текст Close (Закрити)

2023-08-24 08:05 UTC, BogdanGlazkov commented on tailwind.config.js
> +        bgModal: '#A3A3A3E6',
Що це за колір?)

2023-08-24 08:07 UTC, melyasanya commented on tailwind.config.js
> +        bgModal: '#A3A3A3E6',
> Що це за колір?)

це фон модалки

2023-08-24 08:14 UTC, melyasanya commented on src/components/ModalForm/ModalForm.jsx
> +              </button>
> 

додав

2023-08-24 08:16 UTC, melyasanya commented
> Думаю не варто жорстко прив'язувати модалку до форми. Краще зробити модалку універсальною, а форму прокидати в неї як children

Я не впевнений в цьому, тут все зроблено конкретно під Feedback форму, тому я не думаю що в цьому є сенс

2023-08-24 12:16 UTC, BogdanGlazkov commented on tailwind.config.js
> +        bgModal: '#A3A3A3E6',
Є такі hex кольори з 8 знаків?)
hex перекладається 6

2023-08-24 14:56 UTC, nadiakhoptiuk requested changes

2023-08-24 14:56 UTC, nadiakhoptiuk commented on tailwind.config.js
> +        bgModal: '#A3A3A3E6',
є, якщо там є альфа-канал

2023-08-24 14:56 UTC, nadiakhoptiuk commented on src/utils/sendMessageTelegram.js
> +  const url = `https://api.telegram.org/bot${process.env.NEXT_PUBLIC_TELEGRAM_API_KEY}/sendMessage?chat_id=${process.env.NEXT_PUBLIC_TELEGRAM_DIALOGUE_KEY}`;
додай, будь ласка, змінні (назви) до .env.example

2023-08-24 14:56 UTC, nadiakhoptiuk commented on src/components/ModalForm/ModalForm.jsx
> +      <div className="bg-bgModal fixed left-0 right-0 top-0 bottom-0 flex justify-center items-center backdrop-blur-[12.5px] ">
на всіх девайсах модалку краще центрувати посередині бекдропа по висоті

2023-08-24 14:56 UTC, nadiakhoptiuk commented on src/components/ModalForm/ModalForm.jsx
> +            className="fixed inset-0 overflow-y-scroll"
overflow-y-auto виправити, бо видно контейнер скролбара

2023-08-24 14:56 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +      "placeholder": "+38 (097) 12 34 567",
змінити плейсхолдери згідно із макетом

2023-08-24 15:22 UTC, nadiakhoptiuk requested changes

2023-08-24 15:22 UTC, nadiakhoptiuk commented on src/components/FeedbackForm/FeedbackForm.jsx
> +        localStorage.clear();
ця функція очистить повністю локальне сховище, краще користуватися setItem, в даному випадку зручніше писати його як обєкт з ключами, використовуючи json.stringify

2023-08-24 15:38 UTC, ginkosoul commented on tailwind.config.js
> +        bgModal: '#A3A3A3E6',
аналог rgba 
alpha - прозорість
00 - 0% FF- 100%(або навпаки)

2023-08-25 07:32 UTC, BogdanGlazkov requested changes

2023-08-25 07:32 UTC, BogdanGlazkov commented on src/utils/clearLocalStorage.js
> +  });
map() повертає нам новий масив такої ж довжини. Якщо він нам не потрібен, краще використати forEach

2023-08-25 07:32 UTC, BogdanGlazkov commented on src/utils/sendMessageTelegram.js
> +  const url = `https://api.telegram.org/bot${process.env.NEXT_PUBLIC_TELEGRAM_API_KEY}/sendMessage?chat_id=${process.env.NEXT_PUBLIC_TELEGRAM_DIALOGUE_KEY}`;
Не зроблено

2023-08-25 07:32 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +  const onSubmit = data => {
data тут можна не передавати, бо ми беремо її з пропсів, а не під час виклику функції

2023-08-25 08:00 UTC, BogdanGlazkov requested changes

2023-08-25 08:00 UTC, BogdanGlazkov commented on src/components/ApplyButton/ApplyButton.jsx
> +      <ModalForm toggleModal={toggleModal} isOpen={isOpen} data={formData} />
Перевірити btnClose, бо зараз воно undefined

2023-08-25 08:00 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      >
На мобілці не скролиться догори, не видно кнопку закриття https://prnt.sc/o3BDWuRm4p3m

2023-08-25 08:00 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          </p>
Додати line-height, або висоту строки, або падінги згідно макету

2023-08-26 10:37 UTC, BogdanGlazkov requested changes

2023-08-26 10:37 UTC, BogdanGlazkov commented on src/app/(server)/api/form/route.js
> +import { mailOptions, transporter } from '@/utils/nodemailer';
Думаю зайва папка (server) не потрібна, у нас не буде так багато файлів тут

2023-08-26 10:37 UTC, BogdanGlazkov commented on tailwind.config.js
>          headerBg: 'rgba(255, 255, 255, 0.5)',
Зайві змінні не потрібні. Це просто білий колір (white) з прозорістю 50% (opacity-50)

2023-08-26 10:37 UTC, BogdanGlazkov commented on dictionaries/uk.json
> +      "placeholder": "+380971234567",
Виправити також placeholder у англ версії

2023-08-26 10:37 UTC, BogdanGlazkov commented on src/utils/sendEmail.js
> +  fetch('/api/form', {
Використати axios

2023-08-26 10:37 UTC, BogdanGlazkov commented on src/app/[locale]/globals.css
> +} */
Видалити, якщо це не потрібно

2023-08-26 10:37 UTC, BogdanGlazkov commented on src/app/[locale]/globals.css
>    }
@apply достатньо 1 раз, а далі довгий перелік стилів

2023-08-26 10:37 UTC, BogdanGlazkov commented on src/components/ApplyButton/ApplyButton.jsx
> +      >
onClick={toggleModal}

2023-08-26 10:37 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +  const onSubmit = data => {
Не виправлено.
const onSubmit = () => {

2023-08-26 10:37 UTC, BogdanGlazkov commented on src/components/FeedbackForm/FeedbackForm.jsx
> +          </p>
Не виправлено https://prnt.sc/fJNr3NKCHZJL

2023-08-26 10:37 UTC, BogdanGlazkov commented on src/components/index.js
>  export * from './VideoPlayer/VideoPlayer';
Не виправлено

2023-08-26 10:37 UTC, BogdanGlazkov commented on src/utils/clearLocalStorage.js
> +  keysArray.forEach(el => {
Якщо висля стрілки йде тільки один вираз, фігурні дужки не потрібні (синтаксис неявного повернення). Тобто всю цю функцію можна записати у одну строку

2023-08-26 10:55 UTC, melyasanya commented on src/app/(server)/api/form/route.js
> +import { mailOptions, transporter } from '@/utils/nodemailer';
наскільки я знайшов інфу, апішку треба створювати в папці (server)

2023-08-26 10:55 UTC, melyasanya commented on tailwind.config.js
>          headerBg: 'rgba(255, 255, 255, 0.5)',
headerBg це не моя змінна, я її з деву злив

2023-08-26 10:56 UTC, melyasanya commented on src/utils/sendEmail.js
> +  fetch('/api/form', {
це ще вчорашній коміт, в останньому там axios

2023-08-26 10:57 UTC, melyasanya commented on src/app/[locale]/globals.css
>    }
це теж не моє

2023-08-26 11:27 UTC, BogdanGlazkov approved these changes

2023-08-26 13:24 UTC, nadiakhoptiuk requested changes

2023-08-26 13:24 UTC, nadiakhoptiuk commented on .env.example
не можна пушити на гітхаб ключі, і світити їх.
тут тільки назви мають бути

лапки зайві

2023-08-26 13:55 UTC, nadiakhoptiuk requested changes

2023-08-26 13:55 UTC, nadiakhoptiuk commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      reset();
чомусь не очистилась після відправки, + не оновився локалсторедж чомусь (перед відправкою він скинувся на попереднє значення, бо я дописувала @gmail.com)
https://prnt.sc/cEtarvtVqLrn
https://prnt.sc/bjNq-2Ki0foP

іноді очищається, іноді ні..

2023-08-26 13:55 UTC, nadiakhoptiuk commented on src/components/FeedbackForm/FeedbackForm.jsx
> +        onChange={onChange}
onChange={onChange} вішається на input, у форми не бачила такої події

2023-08-26 13:55 UTC, nadiakhoptiuk commented on src/components/FeedbackForm/FeedbackForm.jsx
> +      {isLoading && (
не дуже красиво виглядає спінер поверх форми..  краще б він або замість форми був, або, як на мене, замість тексту у кнопці (але зменшити)

2023-08-28 13:41 UTC, nadiakhoptiuk approved these changes

2023-08-28 13:41 UTC, merged