Feature/hero
SoftRyzen-internship/ambidexter pull request #23
Opened 2023-08-22 10:47 UTC by OleksiiMatveichuk

2023-08-22 12:45 UTC, BogdanGlazkov requested changes

2023-08-22 12:45 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +    <section className="bg-heroBg bg-no-repeat bg-top bg-cover pt-20 md:pt-[75px] xl:pt-[93px] min-h-[420px] md:min-h-[609px] xl:min-h-[1044px] z-[-3]">
Тут z-індекс нічого не дає, фон завжди буде нижче, ніж контент

2023-08-22 12:45 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +    speciality: PropTypes.arrayOf(PropTypes.array.isRequired).isRequired,
Розписати глибше, до строки

2023-08-22 12:45 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +            alt="Галушка Кирило"
alt={title}

2023-08-22 12:45 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
>              <ul className="flex flex-col gap-2 md:gap-3 xl:gap-6">
Зменшити line-height

2023-08-22 12:45 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
>              <ul className="flex flex-col gap-2 md:gap-3 xl:gap-6">
Зменшити line-height

2023-08-22 13:19 UTC, nadiakhoptiuk requested changes
ідея в тому, щоб позбутись додаткових обгорток і полегшити позиціонування. 
краще задати на контейнер верхній падінг і хоча б лівий блок абсолютом не вираховувати (статік), а правий уже доведеться абсолютом.

2023-08-22 13:19 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.jsx
> +    <section className="bg-heroBg bg-no-repeat bg-top bg-cover pt-20 md:pt-[75px] xl:pt-[93px] min-h-[420px] md:min-h-[609px] xl:min-h-[1044px] z-[-3]">
https://prnt.sc/0_aVVK0TEe1x
https://prnt.sc/hrXf-xkh18af

трохи не такі відступи

висота секції (моб) 420+40 = 460, тоді буде за макетом
таблет - 689
десктоп - 1204

2023-08-22 13:19 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.jsx
> +        <div className="relative flex justify-center md:text-base xl:text-large font-medium w-full h-full">
<div className="relative flex justify-center md:text-base xl:text-large font-medium w-full h-full">

цей дів прибрати, клас перенести на контейнер.
додати падінги md:pt-[63px] xl:pt-[124px]


сам контейнер - додати клас 

`export const Container = ({ children, className ='' }) => {
  return <div className={`container ${className}`}>{children}</div>;
};

Container.propTypes = {
  children: PropTypes.node.isRequired,
  className: PropTypes.string,
};`

2023-08-22 13:19 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.jsx
> +          <div className="flex flex-col md:gap-28 xl:gap-64 min-w-max absolute top-0 left-0 md:top-[53px] xl:top-[106px] z-10">
прибрати absolute, додати mr-auto

2023-08-22 13:19 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.jsx
> +          <div className="text-end flex flex-col items-end gap-12 md:gap-[68px] xl:gap-[120px] absolute top-[61px] right-0 md:top-[42px] xl:top-[62px] z-20">
тут змінити: right-5 md:right-10 xl:right-20 md:top-[52px] xl:top-[80px]

2023-08-23 09:14 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
> +    <section className="bg-heroBg bg-no-repeat bg-top bg-cover pt-20 md:pt-[75px] xl:pt-[93px] min-h-[420px] md:min-h-[609px] xl:min-h-[1044px] z-[-3]">
+

2023-08-23 09:15 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
> +            alt="Галушка Кирило"
+

2023-08-23 09:42 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
>              <ul className="flex flex-col gap-2 md:gap-3 xl:gap-6">
+

2023-08-23 09:42 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
>              <ul className="flex flex-col gap-2 md:gap-3 xl:gap-6">
+

2023-08-23 09:46 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
> +    <section className="bg-heroBg bg-no-repeat bg-top bg-cover pt-20 md:pt-[75px] xl:pt-[93px] min-h-[420px] md:min-h-[609px] xl:min-h-[1044px] z-[-3]">
+

2023-08-23 10:12 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
> +        <div className="relative flex justify-center md:text-base xl:text-large font-medium w-full h-full">
+

2023-08-23 10:12 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
> +          <div className="flex flex-col md:gap-28 xl:gap-64 min-w-max absolute top-0 left-0 md:top-[53px] xl:top-[106px] z-10">
+

2023-08-23 10:15 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
> +          <div className="text-end flex flex-col items-end gap-12 md:gap-[68px] xl:gap-[120px] absolute top-[61px] right-0 md:top-[42px] xl:top-[62px] z-20">
+

2023-08-23 10:29 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
> +    speciality: PropTypes.arrayOf(PropTypes.array.isRequired).isRequired,
+

2023-08-23 12:16 UTC, BogdanGlazkov requested changes

2023-08-23 12:16 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +            height={951}
У тега Image скрізь прописуємо quality={100} (вимога техліда)

2023-08-23 12:16 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +            height={951}
Не зроблено

2023-08-23 12:16 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +export const Hero = ({ data, icons }) => {
Зробити деструктуризацію data, за прикладом інших секцій

2023-08-23 12:16 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
>  import PropTypes from 'prop-types';
PropTypes в самому низу сторінки, тому краще і тут їх посунути вниз)

2023-08-23 12:16 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +        <div className="flex flex-col md:gap-28 xl:gap-64 min-w-max relative z-10 mr-auto">
Якщо це не абсолют, z-10 вже не треба

2023-08-23 12:16 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +        <div className="text-end flex flex-col items-end gap-12 md:gap-[68px] xl:gap-[120px] absolute top-[61px] right-5 md:right-10 xl:right-20 md:top-[52px] xl:top-[80px] z-20">
Якщо це перший рівень, то z-10

2023-08-23 12:32 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
> +        <div className="text-end flex flex-col items-end gap-12 md:gap-[68px] xl:gap-[120px] absolute top-[61px] right-5 md:right-10 xl:right-20 md:top-[52px] xl:top-[80px] z-20">
Не перший. Це третій. починаю я із z-0

2023-08-23 12:34 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
> +export const Hero = ({ data, icons }) => {
![image](https://github.com/SoftRyzen-internship/ambidexter/assets/126767121/359c12ab-14e2-4885-86ae-b3b3a1731e64)

2023-08-23 12:35 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
> +        <div className="flex flex-col md:gap-28 xl:gap-64 min-w-max relative z-10 mr-auto">
це вимушене рішення, бо треба щоб воно було між картинкою і правим блоком

2023-08-23 12:35 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
> +            height={951}
+

2023-08-23 12:44 UTC, OleksiiMatveichuk commented on src/sections/Hero/Hero.jsx
>  import PropTypes from 'prop-types';
+

2023-08-23 12:46 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +        <div className="flex flex-col md:gap-28 xl:gap-64 min-w-max relative z-10 mr-auto">
Все ок, просто я relative не побачив)

2023-08-23 12:46 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +        <div className="text-end flex flex-col items-end gap-12 md:gap-[68px] xl:gap-[120px] absolute top-[61px] right-5 md:right-10 xl:right-20 md:top-[52px] xl:top-[80px] z-20">
Ок

2023-08-23 12:48 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +export const Hero = ({ data, icons }) => {
+

2023-08-23 12:49 UTC, BogdanGlazkov approved these changes

2023-08-23 13:08 UTC, nadiakhoptiuk approved these changes

2023-08-23 13:09 UTC, merged