Bugs/about school
SoftRyzen-internship/ambidexter pull request #29
Opened 2023-08-24 13:49 UTC by olegvoskovets

2023-08-24 16:01 UTC, nadiakhoptiuk requested changes

2023-08-24 16:01 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +      }  bg-headerBg `}
це не найкраще рішення:
https://prnt.sc/-Ya1TXfi4PX0

потрібно додавати фон в момент скролу

2023-08-24 16:01 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
>      >
пофіксити блюр при перезавантаженні сторінки на секціях внизу

2023-08-24 16:01 UTC, nadiakhoptiuk commented on src/components/Features/Features.jsx
> +  if (timerId.current === null && inView) {
цей код в клієнтському компоненті, його треба помістити в юзефект. + очищати інтервал на розмонтування

2023-08-25 09:06 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
>      >
ок

2023-08-25 09:45 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +      }  bg-headerBg `}
поправив

2023-08-25 09:46 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
>      >
зробив

2023-08-25 10:10 UTC, olegvoskovets commented on src/components/Features/Features.jsx
> +  if (timerId.current === null && inView) {
зробив

2023-08-25 14:31 UTC, nadiakhoptiuk approved these changes

2023-08-25 14:31 UTC, merged