update: something went wrong with husky
SoftRyzen-internship/ambidexter pull request #3
Opened 2023-08-16 19:43 UTC by ginkosoul

2023-08-16 19:55 UTC, ginkosoul commented
oh... forgot about header... DON'T MERGE... w8 for another commit

2023-08-17 07:19 UTC, BogdanGlazkov approved these changes

2023-08-17 07:19 UTC, BogdanGlazkov commented
Nice

2023-08-17 08:48 UTC, nadiakhoptiuk requested changes

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +    "mainTitle": "Галушка Кирило"
на що в даному випадку буде ссилатися Hero секція? 
якщо ти вносиш зміни у файл з даними, потрібно змінити властивості об'єкта там, де вони використовуються. 
хіба не було помилки локально?

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +  "schoolName": "Ambidexter",
я думаю, цей ключ зайвий (якщо ти для лого планував використати).
1) назва навряд чи зміниться,
2) нам потрібно розділити рядок на спани

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +  "navigtion": {
опечатка

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +    "educationForma": "ФОРМАТ",
опечатка + можна просто format як в навбарі

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +      "Коуч ораторської та акторської майстерності",
потрібно розділити на 2 ключі (тобто 2 масиви), оскільки це по факту 2 списки на сторінці

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +    "label": "про мене",
це у нас заголовок, краще назвати title

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +      { "title": "1к+", "text": "майстер-класів та індивідуальних занять" },
краще count замість title, це ж просто цифри, спани

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +    "titleMain": "Цілі",
тут доведеться перейменувати subTitle і boldSubTitle, наприклад

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +    "label": "Про школу",
title

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +  "orientedClient": {
title пропущено

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +  "educationFormat": {
тут просто format, нижче title і тд по аналогії з aboutMe

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +    "label": "Курси",
title i нижче subTitle

2023-08-17 08:48 UTC, nadiakhoptiuk commented on dictionaries/uk.json
> +      { "label": "Ораторська майстерність" }
текст для кнопки Дізнатися більше можна додати після ключа cards

2023-08-17 10:15 UTC, ginkosoul commented on dictionaries/uk.json
> +    "mainTitle": "Галушка Кирило"
+

2023-08-17 10:15 UTC, ginkosoul commented on dictionaries/uk.json
> +  "schoolName": "Ambidexter",
+

2023-08-17 10:15 UTC, ginkosoul commented on dictionaries/uk.json
> +  "navigtion": {
+

2023-08-17 10:15 UTC, ginkosoul commented on dictionaries/uk.json
> +    "educationForma": "ФОРМАТ",
+

2023-08-17 10:16 UTC, ginkosoul commented on dictionaries/uk.json
> +      "Коуч ораторської та акторської майстерності",
+

2023-08-17 10:16 UTC, ginkosoul commented on dictionaries/uk.json
> +    "label": "Про школу",
+

2023-08-17 10:16 UTC, ginkosoul commented on dictionaries/uk.json
> +  "orientedClient": {
+

2023-08-17 10:16 UTC, ginkosoul commented on dictionaries/uk.json
> +  "educationFormat": {
+

2023-08-17 10:16 UTC, ginkosoul commented on dictionaries/uk.json
> +    "label": "Курси",
+

2023-08-17 10:16 UTC, ginkosoul commented on dictionaries/uk.json
> +    "label": "Курси",
+

2023-08-17 10:16 UTC, ginkosoul commented on dictionaries/uk.json
> +      { "label": "Ораторська майстерність" }
done

2023-08-17 11:23 UTC, nadiakhoptiuk approved these changes

2023-08-17 11:23 UTC, merged