Feature/comment
SoftRyzen-internship/ambidexter pull request #31
Opened 2023-08-24 16:20 UTC by OleksiiMatveichuk

2023-08-24 19:46 UTC, BogdanGlazkov requested changes

2023-08-24 19:46 UTC, BogdanGlazkov commented on dictionaries/en.json
> +        "name": "Antanina Anisovich",
Antonina?

2023-08-24 19:46 UTC, BogdanGlazkov commented on dictionaries/en.json
> +        "name": "Юлія",
Julia. Якщо комент англійською, то ім'я теж

2023-08-24 19:46 UTC, BogdanGlazkov commented on dictionaries/uk.json
> +        "name": "Antanina Anisovich",
Тут так само

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/components/CommentCard/CommentCard.jsx
> +    <div className="rounded-10 border-2 border-accent backdrop-blur-[10px] py-8 px-[10px] md:px-[14px] xl:px-6 flex flex-col gap-3 xl:gap-6 items-center md:w-[216px] xl:w-[414px] min-h-[484px] md:min
Висота найбільшої картки у 1,5 рази більша за ту, що на макеті. На інших картках виходить великий нижній марджин. Тому думаю частину тексту доведеться вирізати чи ховати

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/components/MoreReviews/MoreRevievs.jsx
> +      >
Задати hover і focus, як на макеті

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/components/MoreReviews/MoreRevievs.jsx
> +      >
Задати hover і focus, як на макеті

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/components/MoreReviews/MoreRevievs.jsx
> +'use client';
Відступ

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/sections/Comments/Comments.jsx
> +'use client';
Відступ

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/sections/Comments/Comments.jsx
> +  const mobile = useMediaQuery({ maxWidth: 767 });
const isMobile (це boolean, має відповідати на питання так чи ні)

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/utils/getRatingReviews.js
> +  }
Після default не потрібен break, бо це вже кінець світча.
Пропоную по дефолту повертати порожній масив (0 зірок)

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/components/CommentCard/CommentCard.jsx
> +      />
Картинки і текст не співпадають з макетом

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/components/CommentCard/CommentCard.jsx
> +      <div className="flex gap-1">{ratingReviews(rating)}</div>
Замінити svg, щоб не було рамки з фоном

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/sections/Comments/Comments.jsx
> +    <section id={id} className="bg-commentsBg bg-no-repeat bg-center bg-cover">
Блюр накриває текст та картинку на картці

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/sections/Comments/Comments.jsx
> +    <section id={id} className="bg-commentsBg bg-no-repeat bg-center bg-cover">
Картки занадто довгі і нерівні, на планшеті чорна рамка https://prnt.sc/yM4N8aVICgNF

2023-08-24 19:46 UTC, BogdanGlazkov commented on src/sections/Comments/Comments.jsx
> +        <h2 className="mb-6 md:mb-9 xl:mb-16 text-center">{label}</h2>
Перевірити розмір текста на десктопі

2023-08-24 20:08 UTC, OleksiiMatveichuk commented on dictionaries/en.json
> +        "name": "Юлія",
за коментарі ми розмовляли, що вони не перекладаються 
вирішемо

2023-08-24 20:11 UTC, OleksiiMatveichuk commented on src/sections/Comments/Comments.jsx
> +  const mobile = useMediaQuery({ maxWidth: 767 });
![image](https://github.com/SoftRyzen-internship/ambidexter/assets/126767121/c18ef602-9987-4b9c-aae3-09068a33c0d5)
так ось я його використовую, що не так?

2023-08-24 20:17 UTC, OleksiiMatveichuk commented on src/sections/Comments/Comments.jsx
> +    <section id={id} className="bg-commentsBg bg-no-repeat bg-center bg-cover">
Як в тебе це вийшло, для мене загадка))
В мене все працює добре і нічого такого нема)
Буду фіксити. Ще не знаю як але зроблю. За пораду буду вдячний, бо поки що 0 ідей, як хочаб добитись такого ж ефекту, тим паче виправити

2023-08-24 20:22 UTC, OleksiiMatveichuk commented on src/components/CommentCard/CommentCard.jsx
> +      />
Так в нас коментарі не з макета, там є файл зі своїм текстом та фотками. Того і не співпадають. Чи там в іншому проблема? Розміри перевірив, наче все ок
передивлюсь завтра все

2023-08-24 20:26 UTC, OleksiiMatveichuk commented on src/utils/getRatingReviews.js
> +  }
0 - тобто ніяких зірочок не буде. Не певен що так буде краще, бо потрібна хоч якась оцінка. Інакше якщо не поставлять оцінку якісь коменти будуть з оцінкою, а якісь без...
Але, як скажете, так і зроблю

2023-08-24 20:28 UTC, OleksiiMatveichuk commented on dictionaries/uk.json
> +        "name": "Antanina Anisovich",
https://docs.google.com/document/d/1dxaPTmNnrFLZmvuGWoG2BdiPW1nyzeYiArlgpvRnMZo/edit
я так зрозумів, що і в англ версії і в нашій однаково буде. Дізнаюсь завтра

2023-08-24 20:32 UTC, OleksiiMatveichuk commented on src/components/CommentCard/CommentCard.jsx
> +    <div className="rounded-10 border-2 border-accent backdrop-blur-[10px] py-8 px-[10px] md:px-[14px] xl:px-6 flex flex-col gap-3 xl:gap-6 items-center md:w-[216px] xl:w-[414px] min-h-[484px] md:min
За це ми вирішили на зустрічі, спробувати висоту по найбільшому коментарю, щоб подивитись і вирішити. Якщо треба зменшити, я перероблю, тільки пропоную не коментарі зменшувати а overflow hidden, чи щось такого плану. З'явиться скрол але можу спробувати його подстилізувати

2023-08-25 06:53 UTC, OleksiiMatveichuk commented on src/components/CommentCard/CommentCard.jsx
> +      <div className="flex gap-1">{ratingReviews(rating)}</div>
+

2023-08-25 06:59 UTC, OleksiiMatveichuk commented on src/sections/Comments/Comments.jsx
> +        <h2 className="mb-6 md:mb-9 xl:mb-16 text-center">{label}</h2>
+

2023-08-25 07:09 UTC, OleksiiMatveichuk commented on src/components/MoreReviews/MoreRevievs.jsx
> +'use client';
+

2023-08-25 07:09 UTC, OleksiiMatveichuk commented on src/sections/Comments/Comments.jsx
> +'use client';
+

2023-08-25 08:15 UTC, BogdanGlazkov commented on src/sections/Comments/Comments.jsx
> +    <section id={id} className="bg-commentsBg bg-no-repeat bg-center bg-cover">
Треба задавати карткам фіксовану ширину, як на макеті. І наразі задати overflow-hidden або overflow-scroll

2023-08-25 08:20 UTC, BogdanGlazkov commented on src/components/CommentCard/CommentCard.jsx
> +      />
Добре)

2023-08-25 08:21 UTC, BogdanGlazkov commented on src/utils/getRatingReviews.js
> +  }
Значить залишай 5*

2023-08-25 08:23 UTC, BogdanGlazkov commented on src/sections/Comments/Comments.jsx
> +  const mobile = useMediaQuery({ maxWidth: 767 });
Маю на увазі, треба перейменувати. Ми вже використовували цю змінну у інших компонентах, усюди вона називається isMobile

2023-08-25 08:24 UTC, BogdanGlazkov commented on src/sections/Comments/Comments.jsx
> +  const mobile = useMediaQuery({ maxWidth: 767 });
Якщо boolean, назва змінної має починатися з is

2023-08-25 08:24 UTC, BogdanGlazkov commented on src/components/CommentCard/CommentCard.jsx
> +    <div className="rounded-10 border-2 border-accent backdrop-blur-[10px] py-8 px-[10px] md:px-[14px] xl:px-6 flex flex-col gap-3 xl:gap-6 items-center md:w-[216px] xl:w-[414px] min-h-[484px] md:min
Супер

2023-08-25 08:26 UTC, BogdanGlazkov commented on dictionaries/uk.json
> +        "name": "Antanina Anisovich",
Ну це явна помилка, треба усюди виправити. Навіть на макеті Antоnina

2023-08-25 08:26 UTC, BogdanGlazkov commented on dictionaries/en.json
> +        "name": "Юлія",
Коментарі ні, ім'я так

2023-08-25 09:16 UTC, OleksiiMatveichuk commented on src/sections/Comments/Comments.jsx
> +  const mobile = useMediaQuery({ maxWidth: 767 });
+

2023-08-25 09:58 UTC, OleksiiMatveichuk commented on src/utils/getRatingReviews.js
> +  }
+

2023-08-25 09:58 UTC, OleksiiMatveichuk commented on src/components/MoreReviews/MoreRevievs.jsx
> +      >
+

2023-08-25 09:58 UTC, OleksiiMatveichuk commented on src/components/MoreReviews/MoreRevievs.jsx
> +      >
+

2023-08-25 10:19 UTC, OleksiiMatveichuk commented on src/sections/Comments/Comments.jsx
> +    <section id={id} className="bg-commentsBg bg-no-repeat bg-center bg-cover">
Ширина фіксована і так як на макеті, оверфлоу задам але потрібен час щоб стилізувати скролл

2023-08-25 12:16 UTC, BogdanGlazkov approved these changes

2023-08-25 14:36 UTC, merged