Feature/for whom
SoftRyzen-internship/ambidexter pull request #32
Opened 2023-08-24 20:41 UTC by melyasanya

2023-08-25 13:54 UTC, BogdanGlazkov requested changes

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/app/[locale]/globals.css
> +    @apply mx-auto absolute bottom-0 md:bottom-0 md:left-0 z-0 md:w-[422px] md:h-[454px] xl:w-[813px] xl:h-[862px];
bottom-0 md:bottom-0 - класи повторюються

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/components/ForWhomImage/ForWhomImage.jsx
> +      alt=""
alt="Author"

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/components/ForWhomImageBw/ForWhomImageBw.jsx
> +import Image from 'next/image';
Відступ

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/components/ForWhomImageBw/ForWhomImageBw.jsx
> +      alt=""
alt="Author"

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/components/IncorrectForm/IncorrectForm.jsx
> +};
Якщо цей файл з іншої гілки, то можна видалити, щоб не плутатись

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/components/NotificationForm/NotificationForm.jsx
> +};
Якщо цей файл з іншої гілки, то можна видалити, щоб не плутатись

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/components/RelevantFor/RelevantFor.jsx
> +          return (
Фігурні дужки і return можна не писати

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/sections/ForWhomSection/ForWhomSection.jsx
> +};
PropTypes?

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/components/RelevantFor/RelevantFor.jsx
> +};
PropTypes?

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/sections/ForWhomSection/ForWhomSection.jsx
> +    <section id="forWhom">
Id беремо з локалі

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/components/RelevantFor/RelevantFor.jsx
> +  return (
Відступ перед return

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/sections/ForWhomSection/ForWhomSection.jsx
> +        <SectionTitle text={title} />
Передати пропсом нижній відступ

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/sections/ForWhomSection/ForWhomSection.jsx
> +        </div>
На мобілці розмір картинки має бути меншим.
На десктопі картинка має бути нижче

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/components/RelevantFor/RelevantFor.jsx
> +              <p className="w-[184px] md:text-middle leading-[1.15] xl:w-[357px] xl:text-large">
leading-[1.28] md:leading-[1.2]

2023-08-25 13:54 UTC, BogdanGlazkov commented on src/components/RelevantFor/RelevantFor.jsx
> +              className={`flex gap-[${mobileGap}] justify-start items-center w-[216px] md:gap-[16px] xl:w-[413px]`}
На мобілці немає відступа https://prnt.sc/gzNqUhSsyyII

2023-08-25 14:42 UTC, nadiakhoptiuk commented on src/components/ForWhomImageBw/ForWhomImageBw.jsx
> +      alt=""
краще мабуть, писати Кирило здивований або щось точніше)

2023-08-25 20:30 UTC, BogdanGlazkov approved these changes

2023-08-26 13:04 UTC, nadiakhoptiuk approved these changes

2023-08-26 13:19 UTC, merged