Feature/base styles
SoftRyzen-internship/ambidexter pull request #4
Opened 2023-08-16 19:44 UTC by BogdanGlazkov

Check please

2023-08-16 20:15 UTC, ginkosoul commented
public/icons/orator.svg, public/icons/actor.svg - can't see a reason why?.. why this images are SVG's?..

2023-08-17 08:15 UTC, nadiakhoptiuk requested changes

2023-08-17 08:15 UTC, nadiakhoptiuk commented on public/icons/down.svg
перейменуй якось на arrow-down можливо.

2023-08-17 08:15 UTC, nadiakhoptiuk commented on public/icons/orator.svg
давай спробуємо ці дві картинки викачати в png, значно менше важать, як мінімум у 3 рази

2023-08-17 08:15 UTC, nadiakhoptiuk commented on public/images/arrow-right.png
ці стрілки треба вектором викачувати

2023-08-17 08:15 UTC, nadiakhoptiuk commented on public/images/format-arrows.png
це також вектор, і можливо варто розділити. між ними різні відступи, не факт що співпаде як на макеті

2023-08-17 08:15 UTC, nadiakhoptiuk commented on public/images/free-sm.png
тут не потрібно 2 зображення, одне максимального розміру з повним зеленим кругом

2023-08-17 08:15 UTC, nadiakhoptiuk commented on public/images/review7.jpg
це фото можливо потім треба буде замінити, може дизайнер його кропне по іншому

2023-08-17 08:15 UTC, nadiakhoptiuk commented on public/images/tick-circle.png
ці маркери обидва викачати вектором

2023-08-17 08:15 UTC, nadiakhoptiuk commented on public/images/tick.png
це також вектор має бути

2023-08-17 08:15 UTC, nadiakhoptiuk commented on src/app/[locale]/globals.css
> +  color: #222;
давай уже писати через @apply і тейлвінд.
css тільки для того, що складно стилізується

2023-08-17 08:15 UTC, nadiakhoptiuk commented on src/app/[locale]/globals.css
> +.container {
контейнер не потрібно додавати як клас, він уже в тейлвінді в конфігу налаштований і автоматом приміняється, глянь локально

2023-08-17 08:15 UTC, nadiakhoptiuk commented on src/components/Title/Title.jsx
> +      <h3 className="mainText">{text}</h3>
чому h3, у нас же h2 немає)

2023-08-17 08:15 UTC, nadiakhoptiuk commented on src/components/Title/Title.jsx
> +      <Image
іконку не варто ставити як image, це просто декоративний елемент. і позбутися діва, котрий огортає

2023-08-17 08:15 UTC, nadiakhoptiuk commented on tailwind.config.js
> +        red: '#FF7272',
потрібно винести усі тексти в конфіг і використовувати звідси

2023-08-17 08:15 UTC, nadiakhoptiuk commented on public/icons/left.svg
arrow-left

2023-08-17 08:15 UTC, nadiakhoptiuk commented on public/icons/right.svg
arrow-right

2023-08-17 08:15 UTC, nadiakhoptiuk commented on src/app/[locale]/globals.css
> +    @apply text-[12px] md:text-[16px] xl:text-[24px] font-medium leading-normal text-black;
тексти простіше писати з конфіга, для цього їх варто туди винести

2023-08-17 08:15 UTC, nadiakhoptiuk commented on src/components/Title/Title.jsx
> +export const Title = ({ text }) => {
краще перейменувати на SectionTitle

2023-08-17 08:19 UTC, nadiakhoptiuk commented
> 



> public/icons/orator.svg, public/icons/actor.svg - не можу зрозуміти чому?.. чому ці зображення належать до SVG?.. Бінарний файл addedBIN +2,98 MB [public/images/school-bg-x2 .png] – чи не можна використовувати оптимізовані зображення, такі як .webp?..

ми не додаємо вебп, некст їх генерує під капотом для браузерів, котрі підтримують вебп

2023-08-17 08:33 UTC, BogdanGlazkov commented on public/images/free-sm.png
Не можу витягнути його з макета. Там круг неповний

2023-08-17 10:10 UTC, nadiakhoptiuk approved these changes

2023-08-17 10:12 UTC, merged