Bugs/comments
SoftRyzen-internship/ambidexter pull request #48
Opened 2023-08-28 16:34 UTC by OleksiiMatveichuk

2023-08-28 17:47 UTC, BogdanGlazkov requested changes

2023-08-28 17:47 UTC, BogdanGlazkov commented on dictionaries/en.json
> +        "alt": "Sirgay"
Serhii

2023-08-28 17:47 UTC, BogdanGlazkov commented on dictionaries/en.json
> +      "ariaLeft": "scrol left",
Left

2023-08-28 17:47 UTC, BogdanGlazkov commented on dictionaries/en.json
> +      "ariaRight": "scrol right"
Right

2023-08-28 17:47 UTC, BogdanGlazkov commented on dictionaries/uk.json
> +        "alt": "Олена"
Альона

2023-08-28 17:47 UTC, BogdanGlazkov commented on dictionaries/uk.json
> +      "ariaLeft": "прокрутіть ліворуч",
Ліворуч

2023-08-28 17:47 UTC, BogdanGlazkov commented on dictionaries/uk.json
> +      "ariaRight": "прокрутити праворуч"
Праворуч

2023-08-29 07:14 UTC, BogdanGlazkov approved these changes

2023-08-29 07:42 UTC, BogdanGlazkov approved these changes

2023-08-29 08:17 UTC, nadiakhoptiuk approved these changes

2023-08-29 08:21 UTC, merged