Feature/nav bar
SoftRyzen-internship/ambidexter pull request #6
Opened 2023-08-17 11:55 UTC by olegvoskovets

2023-08-17 13:33 UTC, nadiakhoptiuk requested changes

2023-08-17 13:33 UTC, nadiakhoptiuk commented on public/icons/close_mobile_menu.svg
іконки ці вже додав Богдан

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/app/[locale]/page.jsx
> +      <AboutSchool data={localeData} />
тут краще забирати точково з localeData, для героя потім теж змінимо

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/ButtonBtnMobile/ButtonBtnMobile.jsx
> +export const ButtonBtnMobile = () => {
потрібно робити відступи до компонента для читабельності

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/ButtonBtnMobile/ButtonBtnMobile.jsx
> +import { MobileMenu } from '../MobileMenu/MobileMenu';
імпортуємо за усіма правилами.

import React, { useState } from 'react';
import Image from 'next/image';

import { MobileMenu } from '../MobileMenu/MobileMenu';

import menuBtn from 'public/icons/menuIcon.svg';

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/ButtonBtnMobile/ButtonBtnMobile.jsx
> +  const [openMenu, setOpenMenu] = useState(false);
це стан, він повинен мати назву, на яку в нас відповідь так/ні (буль).

краще назву давати співзвучну питанню: isMenuOpen

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/ButtonBtnMobile/ButtonBtnMobile.jsx
> +  const handleClick = () => {
handleMenuToggle більш влучно, хоча може бути і так

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/ButtonBtnMobile/ButtonBtnMobile.jsx
> +        <Image
треба @svgr/webpack поставити до залежностей розробки і імпортувати іконки як компоненти

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/LinkNavBar/LinkNavBar.jsx
> +import { Link } from 'react-scroll';
можна зовнішні імпорти всі вкупі, без відступів. єдине, що реакт найвище, далі некст

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/LinkNavBar/LinkNavBar.jsx
> +      to={`${link}`}
to={link}

додати класи для активного посилання

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +export const LocaleSwitcher = ({ className }) => {
propTypes додати

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +  console.log('className', className);
логи прибрати

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +      className={`${className} uppercase text-[12px]   md:flex gap-6 xl:gap-3 md: navBar-text  `}
md: без властивостей

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
>              {locale}
тут треба трішки поправити, бо за макетом у нас UA, а міжнародний стандарт uk
так, і треба поміняти місцями en i ua - за макетом

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +import { SocialNetworks } from '../SocialNetworks/SocialNetworks';
впорядкувати імпорти

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +                ? ' font-bold text-activ_nav  hover:text-accent focus:text-accent '
ці лінки на телефоні мають більші розміри, щоб можна було тапнути

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +        <div className="flex justify-between items-center">
цей дів зайвий, ці стилі на контейнер можна додати

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +          <button type="button" className="md:hidden cursor-pointer">
кнопка має більші розміри

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +export const MobileMenu = ({ handleClick }) => {
додати типізацію.

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +import { LinkNavBar } from '../LinkNavBar/LinkNavBar';
впорядкувати імпорти

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +  className: PropTypes.string,
handleClick додати

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +  const { locale } = useParams();
у нас є локаль у лейауті, 
 const localeData = await getDictionary(locale);

і просто прокинути в хедер locale.navigation чи що там потрібно пропсом

не бачу причини всюди окремо запускати функцію, яка завантажує всі словники.
+ тут useParams одразу змінюють компонент на клієнтський

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/components/SocialNetworks/SocialNetworks.jsx
> +  }, [locale]);
те, саме що і в навбарі писала

2023-08-17 13:33 UTC, nadiakhoptiuk commented on tailwind.config.js
> +        activ_nav: '#a1a1a1',
краще вже по аналогії можливо, grey

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/sections/AboutSchool/AboutSchool.jsx
> +  console.log('AboutSchool', data);
логи прибрати

2023-08-17 13:33 UTC, nadiakhoptiuk commented on src/sections/AboutSchool/AboutSchool.jsx
> +  data: PropTypes.any,
прописати типізацію, яка нам може допомогти чимось

2023-08-17 16:38 UTC, olegvoskovets commented on src/components/MobileMenu/MobileMenu.jsx
> +import { SocialNetworks } from '../SocialNetworks/SocialNetworks';
ок

2023-08-17 16:38 UTC, olegvoskovets commented on src/components/MobileMenu/MobileMenu.jsx
> +        <div className="flex justify-between items-center">
без нього не вірно працює

2023-08-17 16:38 UTC, olegvoskovets commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
>              {locale}
ок

2023-08-17 16:39 UTC, olegvoskovets commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +      className={`${className} uppercase text-[12px]   md:flex gap-6 xl:gap-3 md: navBar-text  `}
видалив поки. не памятаю може щось забув прописати

2023-08-17 16:39 UTC, olegvoskovets commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +  console.log('className', className);
ок

2023-08-17 16:39 UTC, olegvoskovets commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +export const LocaleSwitcher = ({ className }) => {
ок

2023-08-17 16:40 UTC, olegvoskovets commented on src/components/LinkNavBar/LinkNavBar.jsx
> +      to={`${link}`}
щось поки в мене не хоче працювати активний елемент. запитаю при зустрічі

2023-08-17 16:40 UTC, olegvoskovets commented on src/components/LinkNavBar/LinkNavBar.jsx
> +import { Link } from 'react-scroll';
ок

2023-08-17 16:41 UTC, olegvoskovets commented on src/components/ButtonBtnMobile/ButtonBtnMobile.jsx
> +        <Image
поставив але щось десь не зробив вірно і не запрацювало дало помилки. запитаю при зустрічі

2023-08-17 16:41 UTC, olegvoskovets commented on src/components/ButtonBtnMobile/ButtonBtnMobile.jsx
> +  const handleClick = () => {
зробив

2023-08-17 16:41 UTC, olegvoskovets commented on src/components/ButtonBtnMobile/ButtonBtnMobile.jsx
> +  const [openMenu, setOpenMenu] = useState(false);
поправив

2023-08-17 16:41 UTC, olegvoskovets commented on src/components/ButtonBtnMobile/ButtonBtnMobile.jsx
> +import { MobileMenu } from '../MobileMenu/MobileMenu';
ок

2023-08-17 16:41 UTC, olegvoskovets commented on src/components/ButtonBtnMobile/ButtonBtnMobile.jsx
> +export const ButtonBtnMobile = () => {
ок

2023-08-17 16:42 UTC, olegvoskovets commented on public/icons/close_mobile_menu.svg
поміяв. коли робив не було інших

2023-08-17 16:42 UTC, olegvoskovets commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +                ? ' font-bold text-activ_nav  hover:text-accent focus:text-accent '
зробив

2023-08-17 16:45 UTC, olegvoskovets commented on src/components/MobileMenu/MobileMenu.jsx
> +          <button type="button" className="md:hidden cursor-pointer">
зробив

2023-08-17 16:47 UTC, olegvoskovets commented on src/components/MobileMenu/MobileMenu.jsx
> +export const MobileMenu = ({ handleClick }) => {
зробив

2023-08-17 16:48 UTC, olegvoskovets commented on src/components/NavBar/NavBar.jsx
> +import { LinkNavBar } from '../LinkNavBar/LinkNavBar';
ок

2023-08-17 16:49 UTC, olegvoskovets commented on src/components/NavBar/NavBar.jsx
> +  className: PropTypes.string,
ok

2023-08-17 17:03 UTC, olegvoskovets commented on src/sections/AboutSchool/AboutSchool.jsx
> +  console.log('AboutSchool', data);
ok

2023-08-17 17:05 UTC, olegvoskovets commented on src/sections/AboutSchool/AboutSchool.jsx
> +  data: PropTypes.any,
поки не змінив . приходять данні різної структури. як зробитьи поки не знаю

2023-08-17 17:07 UTC, olegvoskovets commented on src/components/NavBar/NavBar.jsx
> +  const { locale } = useParams();
сам розумію що треба якось поправити но в мене йдуть постійно помилки

2023-08-18 15:38 UTC, nadiakhoptiuk requested changes

2023-08-18 15:38 UTC, nadiakhoptiuk commented on next.config.js
> +  // webpack: config => {
чому закоментовано?

2023-08-18 15:38 UTC, nadiakhoptiuk commented on public/icons/menuIcon.svg
іконка меню також не потрібна ще одна

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/app/[locale]/globals.css
> +
@tailwind components;
@tailwind utilities;

дублюється

body теж

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/app/[locale]/layout.jsx
> +import Header from '@/layout/Header/Header';
чому змінився імпорт? там же реекспорт був з папки лейаут

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +export default async function Header({ params }) {
params - зарезервоване слово, використовується на сторінках, лейауті, але в компонентах наче ні. і в даноу випадку це не params, а просто пропс. треба дати йому іншу назву, бо ми тут все заплутаємо

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +import { ButtonBtnMobile } from '@/components/ButtonBtnMobile/ButtonBtnMobile';
здійснити реекспорт усіх інших компонентів з індексного файла

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +        <div className="flex items-center justify-between">
тут зайвий дів, ці стилі перенести на контейнер

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/components/SocialNetworks/SocialNetworks.jsx
> +  }, [locale]);
впорядкувати імпорти
не використовувати тут useParams
прокинути дані пропом

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +          <LocaleSwitcher className="hidden" />
чому навбар і мова завжди приховані?

краще приховувати не через css, а через рендер за умови, використовуючи react-responsive

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/sections/AboutSchool/AboutSchool.jsx
> +// import { aboutSchool } from '../../../dictionaries/en.json';
коментарі, логи

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/sections/AboutSchool/AboutSchool.jsx
> +  const { aboutSchool } = data;
провести деструктуризацію на сторінці і прокинути в data aboutSchool + змінити тут проп тайпи

2023-08-18 15:38 UTC, nadiakhoptiuk commented on tailwind.config.js
> +        activ_nav: '#a1a1a1',
назвати по аналогії

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +            <Image
використати svgr/webpack

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/components/LinkNavBar/LinkNavBar.jsx
> +        href={`#${link}`}
href="/" - він потрібен тільки для табуляції

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
>              {locale}
тут UA так і не реалізовано

2023-08-18 15:38 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +import { SocialNetworks } from '../SocialNetworks/SocialNetworks';
реекспорт через index.js виконати

2023-08-18 16:00 UTC, nadiakhoptiuk requested changes

2023-08-18 16:00 UTC, nadiakhoptiuk commented on src/sections/AboutSchool/AboutSchool.jsx
> +          <ul className="w-full  text-[8px] font-medium md:text-[16px] xl:text-[24px] flex flex-wrap justify-around gap-x-5 gap-y-1 md:gap-y-6 xl:gap-y-12">
я сьогодні казала, по 3 колонки на всіх девайсах

2023-08-18 16:00 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +    <header className="py-6 px-5 fixed w-full ">
хедер не повинен мати падінги з боків, вони на контейнері стоять

2023-08-18 16:00 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +          <Logo isColored={true} />
лого і кнопку прибираємо. 
у нас є мобільний хедер, в якому в залежності від того чи відкрита менюшка, змінюємо іконку на кнопці. все..
і задаємо z-index
меню має закриватися плавно

2023-08-18 16:00 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +                : '  font-normal  p-3 xl:p-0 hover:text-accent focus:text-accent'
посилання потрібно розтягнути на всю ширину/висоту лішки на мобільному і таблеті

2023-08-18 16:00 UTC, nadiakhoptiuk commented on src/sections/AboutSchool/AboutSchool.jsx
> +          <p className="leading-normal text-[16px] lowercase md:text-[24px] xl:text-[36px]">
відступи не за макетом

2023-08-18 21:09 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +    <header className="py-6 px-5 fixed w-full ">
так я вже бачив

2023-08-18 21:12 UTC, olegvoskovets commented on src/app/[locale]/layout.jsx
> +import Header from '@/layout/Header/Header';
наче не змінював

2023-08-18 21:17 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +export default async function Header({ params }) {
поправив

2023-08-18 21:19 UTC, olegvoskovets commented on src/components/MobileMenu/MobileMenu.jsx
> +            <Image
видалив

2023-08-18 21:22 UTC, olegvoskovets commented on src/components/LinkNavBar/LinkNavBar.jsx
> +        href={`#${link}`}
виправив

2023-08-18 21:24 UTC, olegvoskovets commented on src/sections/AboutSchool/AboutSchool.jsx
> +          <ul className="w-full  text-[8px] font-medium md:text-[16px] xl:text-[24px] flex flex-wrap justify-around gap-x-5 gap-y-1 md:gap-y-6 xl:gap-y-12">
розумію. я казав не перевіряти бо деякі речі перероблюю

2023-08-19 10:24 UTC, olegvoskovets commented on src/sections/AboutSchool/AboutSchool.jsx
> +          <ul className="w-full  text-[8px] font-medium md:text-[16px] xl:text-[24px] flex flex-wrap justify-around gap-x-5 gap-y-1 md:gap-y-6 xl:gap-y-12">
зробив

2023-08-19 10:25 UTC, olegvoskovets commented on src/components/ButtonBtnMobile/ButtonBtnMobile.jsx
> +        <Image
зробив

2023-08-19 10:25 UTC, olegvoskovets commented on src/components/LinkNavBar/LinkNavBar.jsx
> +      to={`${link}`}
зробив

2023-08-19 10:28 UTC, olegvoskovets commented on src/components/MobileMenu/MobileMenu.jsx
> +import { SocialNetworks } from '../SocialNetworks/SocialNetworks';
зробив

2023-08-19 10:29 UTC, olegvoskovets commented on src/components/NavBar/NavBar.jsx
> +  const { locale } = useParams();
зробив

2023-08-19 10:30 UTC, olegvoskovets commented on src/components/SocialNetworks/SocialNetworks.jsx
> +  }, [locale]);
зробив

2023-08-19 10:30 UTC, olegvoskovets commented on tailwind.config.js
> +        activ_nav: '#a1a1a1',
взагалі видалив добавили за мене

2023-08-19 10:31 UTC, olegvoskovets commented on next.config.js
> +  // webpack: config => {
поправив

2023-08-19 10:32 UTC, olegvoskovets commented on public/icons/menuIcon.svg
видалив

2023-08-19 10:34 UTC, olegvoskovets commented on src/app/[locale]/globals.css
> +
видалив. звідки взялось не знаю

2023-08-19 10:35 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +import { ButtonBtnMobile } from '@/components/ButtonBtnMobile/ButtonBtnMobile';
поправив

2023-08-19 11:00 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +        <div className="flex items-center justify-between">
так не хоче працювати

2023-08-20 09:58 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +              onClick={() => handleMenuToggle()}
клік вішаємо на кнопку, а не на іконку

2023-08-20 10:00 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +  const isMobile = useMediaQuery({ maxWidth: 768 });
максимальна ширина 767

2023-08-21 12:25 UTC, nadiakhoptiuk commented on src/app/[locale]/globals.css
> +/* :root {
коментарі прибрати

2023-08-21 12:25 UTC, nadiakhoptiuk commented on i18n.js
> +  locales: ['en', 'ua'],
змінити на uk

2023-08-21 12:25 UTC, nadiakhoptiuk commented on public/icons/menuIcon.svg
ця іконка вже була

2023-08-21 12:25 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +    <header className="flex items-center h-[68px] md:h-[63px] xl:h-[93px] mt-3 md:mt-9 xl:mt-16 fixed w-full  backdrop-blur-[100px] ">
марджин топ потрібно прибрати, бо там залишається порожній простір
меню повинно розтягуватись на весь екран

2023-08-21 12:25 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +        <header className="flex justify-between items-center  mb-6 h-[68px]"></header>
цей тег пустий і зайвий, просто на його висоту додати падінг до мобільного меню

2023-08-21 12:25 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +  //  handleMenuToggle: PropTypes.func,
тут пофіксити

2023-08-21 12:25 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +        <div className="flex justify-between items-center">
позбутися діва, все чудово працює.

     <Container className="flex flex-col gap-9 ">

2023-08-21 12:28 UTC, nadiakhoptiuk commented on src/app/[locale]/globals.css
> +
конфлікти треба акуратно фіксити

2023-08-21 17:42 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +  const isMobile = useMediaQuery({ maxWidth: 768 });
цей компонент я взагалі прибрав

2023-08-21 17:43 UTC, olegvoskovets commented on src/app/[locale]/globals.css
> +/* :root {
прибрав

2023-08-21 17:44 UTC, olegvoskovets commented on i18n.js
> +  locales: ['en', 'ua'],
зроблено

2023-08-21 17:45 UTC, olegvoskovets commented on public/icons/menuIcon.svg
де Ви її знайшли. в мене немає вже такої

2023-08-21 18:52 UTC, olegvoskovets commented on src/components/MobileMenu/MobileMenu.jsx
> +  //  handleMenuToggle: PropTypes.func,
зробив

2023-08-22 07:28 UTC, nadiakhoptiuk commented on public/icons/menuIcon.svg
є у доданих файлах коміта

2023-08-22 07:31 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +    <header className="flex items-center h-[68px] md:h-[63px] xl:h-[93px] mt-3 md:mt-9 xl:mt-16 fixed w-full  backdrop-blur-[100px] ">
меню повинно розтягуватись на весь екран (висота)

2023-08-22 07:42 UTC, nadiakhoptiuk requested changes

2023-08-22 07:42 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +  // mt-3 md:mt-9 xl:mt-16
коментарі почистити

2023-08-22 07:42 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +          <NavBar className="hidden text-[12px]" data={navBar} />
перевірити відступи від набару до кнопок і до соцмереж

2023-08-22 07:42 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +          handleMenuToggle={handleMenuToggle}
меню повинно закриватись на кнопку ESC і також потрібно блокувати скрол сторінки, коли воно відкрите.
+ пофіксити всі z-index, бо секції вилазять над меню

2023-08-22 07:42 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +          <LocaleSwitcher className="hidden" />
`<NavBar className="hidden text-[12px]" data={navBar} />
<LocaleSwitcher className="hidden" />`

ці два рядки потрібно рендерити за умови !isMobile, щоб був чистіше код, а hidden можна прибрати

2023-08-22 07:42 UTC, nadiakhoptiuk commented on dictionaries/en.json
> +  "socialNetworks": "social Networks",
подивись ще ось тут однакові ключі socialNetworks і socialsLabel

2023-08-22 08:52 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +  // mt-3 md:mt-9 xl:mt-16
убрав

2023-08-22 09:14 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +    <header className="flex items-center h-[68px] md:h-[63px] xl:h-[93px] mt-3 md:mt-9 xl:mt-16 fixed w-full  backdrop-blur-[100px] ">
зрозумів нарешті. по макету fixed стояло

2023-08-22 09:34 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +          <NavBar className="hidden text-[12px]" data={navBar} />
ok

2023-08-22 19:29 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +          <LocaleSwitcher className="hidden" />
дуже не гарно виглядає

2023-08-22 19:30 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +          handleMenuToggle={handleMenuToggle}
зробив========= на кнопку ESC і також потрібно блокувати скрол сторінки, коли воно відкрите
пофіксити всі z-index, бо секції вилазять над меню

2023-08-22 19:34 UTC, olegvoskovets commented on src/layout/Header/Header.jsx
> +          <LocaleSwitcher className="hidden" />
hidden повернув. дуже б'є по очах

2023-08-23 09:43 UTC, nadiakhoptiuk approved these changes

2023-08-23 09:43 UTC, merged