update Readmy file
SoftRyzen-internship/ambidexter pull request #69
Opened 2023-09-02 19:10 UTC by olegvoskovets

2023-09-03 12:16 UTC, nadiakhoptiuk requested changes

2023-09-03 12:16 UTC, nadiakhoptiuk commented on README.md
> +  - [Telegram API](https://core.telegram.org/)
телеграм і nodemailer я б звідси прибрала, перший ми не юзаємо як бекенд взагалі, а другий - це технологія, яка інтегрована у наш бекенд для відправки листів.

2023-09-03 12:16 UTC, nadiakhoptiuk commented on READMY.start.md
правильно README - усі файли змінити

2023-09-03 12:16 UTC, nadiakhoptiuk commented on README.md
> +## Screenshots
я б не виділяла як заголовок, а просто скріншот перемістила б під опис сайту (вгорі)

2023-09-03 12:16 UTC, nadiakhoptiuk commented on README.md
тут можна коротко дописати "це сайт, який є візитною карткою ..." має стільки сторінок...,  і що він дає змогу зробити (функціонально)
і потрібно додати посилання на живу сторінку

2023-09-03 12:16 UTC, nadiakhoptiuk commented on README.md
> +  - [React-sckroll](https://www.npmjs.com/package/react-scroll)
Scroll правильно

2023-09-03 12:16 UTC, nadiakhoptiuk commented on README.md
> +  - [JavaSkript](https://uk.javascript.info/)
JavaScript правильно

2023-09-03 12:57 UTC, olegvoskovets commented on README.md
> +  - [Telegram API](https://core.telegram.org/)
+

2023-09-03 12:57 UTC, olegvoskovets commented on READMY.start.md
виправив

2023-09-03 12:57 UTC, olegvoskovets commented on README.md
> +## Screenshots
виправив

2023-09-03 12:58 UTC, olegvoskovets commented on README.md
> +  - [React-sckroll](https://www.npmjs.com/package/react-scroll)
виправив

2023-09-03 12:58 UTC, olegvoskovets commented on README.md
> +  - [JavaSkript](https://uk.javascript.info/)
виправив

2023-09-03 14:51 UTC, nadiakhoptiuk commented on README.md
> +  - [JavaSkript](https://uk.javascript.info/)
не запушено зміни

2023-09-03 16:08 UTC, olegvoskovets commented on README.md
виправив

2023-09-03 16:50 UTC, nadiakhoptiuk commented on README.md
> +  - [Telegram API](https://core.telegram.org/)
ці пакети можна просто у фронтенд перемістити

2023-09-03 17:22 UTC, olegvoskovets commented on README.md
> +  - [Telegram API](https://core.telegram.org/)
зрозумів буквально

2023-09-04 07:06 UTC, nadiakhoptiuk approved these changes

2023-09-04 07:06 UTC, merged